/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedDeliveryRouteImport } from './routes/_authed/delivery'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedOpnameRouteImport } from './routes/_authed/opname'
import { Route as AuthedReceiveRouteImport } from './routes/_authed/receive'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDeliveryRoute = AuthedDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOpnameRoute = AuthedOpnameRouteImport.update({
  id: '/opname',
  path: '/opname',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedReceiveRoute = AuthedReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/delivery': typeof AuthedDeliveryRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/opname': typeof AuthedOpnameRoute
  '/receive': typeof AuthedReceiveRoute
  '/settings': typeof AuthedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/delivery': typeof AuthedDeliveryRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/opname': typeof AuthedOpnameRoute
  '/receive': typeof AuthedReceiveRoute
  '/settings': typeof AuthedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/delivery': typeof AuthedDeliveryRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/opname': typeof AuthedOpnameRoute
  '/_authed/receive': typeof AuthedReceiveRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/delivery'
    | '/onboarding'
    | '/opname'
    | '/receive'
    | '/settings'
    | '/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/delivery'
    | '/onboarding'
    | '/opname'
    | '/receive'
    | '/settings'
    | '/invite/$token'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/delivery'
    | '/_authed/onboarding'
    | '/_authed/opname'
    | '/_authed/receive'
    | '/_authed/settings'
    | '/invite/$token'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/delivery': {
      id: '/_authed/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthedDeliveryRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/opname': {
      id: '/_authed/opname'
      path: '/opname'
      fullPath: '/opname'
      preLoaderRoute: typeof AuthedOpnameRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/receive': {
      id: '/_authed/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof AuthedReceiveRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDeliveryRoute: typeof AuthedDeliveryRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedOpnameRoute: typeof AuthedOpnameRoute
  AuthedReceiveRoute: typeof AuthedReceiveRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDeliveryRoute: AuthedDeliveryRoute,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedOpnameRoute: AuthedOpnameRoute,
  AuthedReceiveRoute: AuthedReceiveRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
