#!/usr/bin/env python3
"""Jobs tooling. One script, three jobs. See README.md.

  python3 docs/jobs/_jobs.py gen                          regenerate BOARD/INCIDENTS/JOURNAL
  python3 docs/jobs/_jobs.py new --type FEAT --title ".."   mint a job (main tree only)
  python3 docs/jobs/_jobs.py new --type INC  --title ".."   mint an incident
  python3 docs/jobs/_jobs.py guard                        PreToolUse hook (internal)

Stdlib only. IDs are one global SN-#### sequence shared by jobs + incidents.
"""
import os
import re
import sys
import json
import subprocess
from datetime import date

JOBS = os.path.dirname(os.path.abspath(__file__))
WO = os.path.join(JOBS, "wo")
INCIDENTS = os.path.join(JOBS, "incidents")
TASK_TYPES = ["FEAT", "FIX", "CHORE", "REFACTOR", "DOCS"]
GEN = "<!-- GENERATED by _jobs.py — do not edit. Regenerate: python3 docs/jobs/_jobs.py gen -->"
JOB_STATUS = ["in-progress", "blocked", "ready", "in-review", "backlog", "done", "cancelled"]
INCIDENT_STATUS = ["open", "investigating", "mitigated", "resolved", "wontfix"]
SN_RE = re.compile(r"^SN-(\d+)\.md$")
ENTRY_RE = re.compile(r"^###\s+(\S+)\s+·\s+([A-Za-z-]+)\s*$")


def parse_doc(path):
    raw = open(path, encoding="utf-8").read()
    fm, body = {}, raw
    m = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n?(.*)$", raw, re.S)
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                fm[k.strip()] = v.strip()
        body = m.group(2)
    entries, lines = [], body.splitlines()
    for i, line in enumerate(lines):
        h = ENTRY_RE.match(line)
        if not h:
            continue
        text = []
        j = i + 1
        while j < len(lines) and not re.match(r"^#{2,3}\s", lines[j]):
            if lines[j].strip():
                text.append(lines[j].strip())
            j += 1
        entries.append({"ts": h.group(1), "kind": h.group(2), "text": " ".join(text)})
    return {"path": path, "fm": fm, "entries": entries}


def list_dir(d):
    if not os.path.isdir(d):
        return []
    return [parse_doc(os.path.join(d, f)) for f in sorted(os.listdir(d)) if SN_RE.match(f)]


def in_worktree():
    g = subprocess.check_output(["git", "rev-parse", "--absolute-git-dir"], text=True).strip()
    c = subprocess.check_output(
        ["git", "rev-parse", "--path-format=absolute", "--git-common-dir"], text=True
    ).strip()
    return g != c


def write(name, text):
    open(os.path.join(JOBS, name), "w", encoding="utf-8").write(text)


def gen():
    jobs = sorted(list_dir(WO), key=lambda t: t["fm"].get("id", ""))  # board sorts by ID
    incidents = list_dir(INCIDENTS)

    board = (
        f"{GEN}\n\n# Board\n\nEvery job, current state, sorted by id. Generated from `wo/` — do not "
        "edit here. Protocol: [README.md](README.md).\n\n"
        "| Updated | ID | Type | Pri | Status | Blocked by | Title | Branch |\n"
        "|---|---|---|---|---|---|---|---|\n"
    )
    for t in jobs:
        f = os.path.basename(t["path"])
        fm = t["fm"]
        board += (
            f"| {fm.get('updated','')} | [{fm.get('id','')}](wo/{f}) | {fm.get('type','')} "
            f"| {fm.get('priority','')} | {fm.get('status','')} | {fm.get('blocked_by','—')} "
            f"| {fm.get('title','')} | {fm.get('branch') or '—'} |\n"
        )
    if not jobs:
        board += "| | | | | | | _no jobs yet_ | |\n"
    write("BOARD.md", board + "\n")

    incidents_sorted = sorted(
        incidents, key=lambda t: INCIDENT_STATUS.index(t["fm"].get("status", "open"))
        if t["fm"].get("status") in INCIDENT_STATUS else 99
    )
    inc = (
        f"{GEN}\n\n# Incidents\n\nOperational incidents. Generated from `incidents/` — do not edit "
        "here. Design-time API gaps (INC-1..6) live in `../discovery/incidents.md`. Protocol: "
        "[README.md](README.md).\n\n"
        "| Logged | ID | Status | Recap | Related | File |\n|---|---|---|---|---|---|\n"
    )
    for t in incidents_sorted:
        f = os.path.basename(t["path"])
        fm = t["fm"]
        inc += (
            f"| {fm.get('created', fm.get('updated',''))} | {fm.get('id','')} | {fm.get('status','')} "
            f"| {fm.get('recap','')} | {fm.get('related','—')} | [{f}](incidents/{f}) |\n"
        )
    if not incidents_sorted:
        inc += "| | | | _none logged_ | | |\n"
    write("INCIDENTS.md", inc + "\n")

    alle = []
    for t in jobs + incidents:
        for e in t["entries"]:
            alle.append({"id": t["fm"].get("id", ""), **e})
    alle.sort(key=lambda e: e["ts"], reverse=True)
    jrn = (
        f"{GEN}\n\n# Journal\n\nEvery log entry across all jobs and incidents, newest first. "
        "Generated. Protocol: [README.md](README.md).\n\n"
    )
    for e in alle:
        jrn += f"- `{e['ts']}` · **{e['id']}** · _{e['kind']}_ — {e['text']}\n"
    if not alle:
        jrn += "_no log entries yet_\n"
    write("JOURNAL.md", jrn + "\n")

    print(f"gen: {len(jobs)} job(s), {len(incidents)} incident(s), {len(alle)} entr(ies).")


def next_id():
    mx = 0
    for d in (WO, INCIDENTS):
        if os.path.isdir(d):
            for f in os.listdir(d):
                m = SN_RE.match(f)
                if m:
                    mx = max(mx, int(m.group(1)))
    return f"SN-{mx + 1:04d}"


def parse_args(argv):
    a = {}
    i = 0
    while i < len(argv):
        if argv[i].startswith("--"):
            a[argv[i][2:]] = argv[i + 1] if i + 1 < len(argv) else ""
            i += 2
        else:
            i += 1
    return a


def new():
    try:
        if in_worktree():
            sys.exit("error: mint jobs/incidents in the MAIN working tree, not a worktree (ids are a shared sequence).")
    except subprocess.CalledProcessError:
        sys.exit("error: not a git repository.")
    a = parse_args(sys.argv[2:])
    typ = a.get("type", "").upper()
    title = a.get("title", "")
    if not typ or not title:
        sys.exit('usage: new --type <FEAT|FIX|CHORE|REFACTOR|DOCS|INC> --title "..." [--epic ..] [--plan ..] [--blocked_by ..] [--lane ..] [--priority ..] [--branch ..] [--related ..] [--introduced ..]')
    sid = next_id()
    d = date.today().isoformat()
    if typ == "INC":
        os.makedirs(INCIDENTS, exist_ok=True)
        path = os.path.join(INCIDENTS, f"{sid}.md")
        body = (
            f"---\nid: {sid}\nrecap: {title}\nstatus: open\nrelated: {a.get('related','-')}\n"
            f"introduced: {a.get('introduced','-')}\ncreated: {d}\nupdated: {d}\n---\n\n"
            "## Detail\n\n<What was observed, impact, scope.>\n\n## Log\n\n"
            f"### {d} · filed\n<How it was found.>\n"
        )
    else:
        if typ not in TASK_TYPES:
            sys.exit(f"error: --type must be one of {', '.join(TASK_TYPES)} or INC")
        os.makedirs(WO, exist_ok=True)
        path = os.path.join(WO, f"{sid}.md")
        body = (
            f"---\nid: {sid}\ntitle: {title}\ntype: {typ}\nstatus: backlog\nepic: {a.get('epic','-')}\n"
            f"plan: {a.get('plan','-')}\nblocked_by: {a.get('blocked_by','-')}\nlane: {a.get('lane','-')}\n"
            f"size: {a.get('size','-')}\nrisk: {a.get('risk','-')}\npriority: {a.get('priority','-')}\n"
            f"branch: {a.get('branch','')}\ncreated: {d}\nupdated: {d}\n---\n\n"
            "## Objective\n\n<What this delivers, from the user's perspective.>\n\n"
            "## References\n\n<Links to the plan / ADRs this executes — thinking lives in ../../plans/ and ../../adr/.>\n\n"
            "## Scope fence\n\n**In scope** - <what to touch>\n\n**Out of scope** - <what not to touch; STOP and escalate if the work needs it>\n\n"
            "## Acceptance gate\n\n- [ ] <criterion>\n- [ ] Lane gate green (BE: go build/vet/test; FE: pnpm typecheck/test/lint)\n\n"
            f"## Log\n\n### {d} · filed\n<Why this job exists; blockers if any.>\n"
        )
    if os.path.exists(path):
        sys.exit(f"error: {path} already exists.")
    open(path, "w", encoding="utf-8").write(body)
    gen()
    print(f"created {path}")


def guard():
    try:
        payload = sys.stdin.read()
        file = (json.loads(payload).get("tool_input") or {}).get("file_path", "")
    except Exception:
        sys.exit(0)
    if not re.search(r"/jobs/(wo|incidents)/SN-\d+\.md$", file):
        sys.exit(0)
    if os.path.exists(file):  # editing an existing job is fine
        sys.exit(0)
    try:
        if not in_worktree():
            sys.exit(0)
    except Exception:
        sys.exit(0)
    sys.stderr.write(
        "Blocked: new jobs/incidents must be minted in the MAIN working tree, not a worktree.\n"
        "Ids are a shared global sequence. In the primary checkout run:\n"
        '  python3 docs/jobs/_jobs.py new --type <TYPE> --title "..."\n'
        "then commit there and rebase this worktree onto it.\n"
    )
    sys.exit(2)


def onread():
    """PostToolUse(Read) hook: enforce the work-in-a-worktree rule.
    When a ready/in-progress job is read from the MAIN checkout (not a worktree),
    remind that job execution belongs in a worktree. Silent otherwise."""
    try:
        file = (json.loads(sys.stdin.read()).get("tool_input") or {}).get("file_path", "")
    except Exception:
        sys.exit(0)
    if not re.search(r"/jobs/wo/SN-\d+\.md$", file) or not os.path.exists(file):
        sys.exit(0)
    try:
        fm = parse_doc(file)["fm"]
    except Exception:
        sys.exit(0)
    if fm.get("status") not in ("ready", "in-progress"):
        sys.exit(0)  # only nudge for jobs being (or about to be) worked
    try:
        if in_worktree():
            sys.exit(0)  # already following the rule
    except Exception:
        sys.exit(0)
    jid = fm.get("id", "this job")
    sys.stderr.write(
        f"Worktree rule: {jid} is '{fm.get('status')}' and you are on the MAIN checkout.\n"
        "Implement jobs in a worktree, not on main - mint ids on main, do the work in a\n"
        "worktree under .wt/ (see CLAUDE.md worktree rules + docs/jobs/README.md). Create one:\n"
        f"  git worktree add .wt/<slug> -b <type>/<slug>\n"
        "then set the job's `branch` and log from there.\n"
    )
    sys.exit(2)  # PostToolUse exit 2 surfaces stderr to the agent (non-blocking; Read already ran)


cmd = sys.argv[1] if len(sys.argv) > 1 else ""
if cmd == "gen":
    gen()
elif cmd == "new":
    new()
elif cmd == "guard":
    guard()
elif cmd == "onread":
    onread()
else:
    sys.exit("usage: python3 docs/jobs/_jobs.py <gen|new|guard|onread>")
