// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batches.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBatch = `-- name: CreateBatch :one
INSERT INTO batches (tenant_id, product_id, batch_no, expiry_date)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, product_id, batch_no, expiry_date, created_at
`

type CreateBatchParams struct {
	TenantID   uuid.UUID
	ProductID  uuid.UUID
	BatchNo    string
	ExpiryDate pgtype.Date
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, createBatch,
		arg.TenantID,
		arg.ProductID,
		arg.BatchNo,
		arg.ExpiryDate,
	)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.BatchNo,
		&i.ExpiryDate,
		&i.CreatedAt,
	)
	return i, err
}

const listBatches = `-- name: ListBatches :many
SELECT id, tenant_id, product_id, batch_no, expiry_date, created_at FROM batches
WHERE tenant_id = $1 AND product_id = $2
ORDER BY expiry_date NULLS LAST, batch_no
`

type ListBatchesParams struct {
	TenantID  uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) ListBatches(ctx context.Context, arg ListBatchesParams) ([]Batch, error) {
	rows, err := q.db.Query(ctx, listBatches, arg.TenantID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Batch
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.BatchNo,
			&i.ExpiryDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
