// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDelivery = `-- name: CreateDelivery :one

INSERT INTO deliveries (tenant_id, sales_order_id, customer_id, warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, doc_number, status, sales_order_id, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type CreateDeliveryParams struct {
	TenantID     uuid.UUID
	SalesOrderID pgtype.UUID
	CustomerID   uuid.UUID
	WarehouseID  uuid.UUID
	DocDate      pgtype.Date
	Notes        string
	ReversesID   pgtype.UUID
	Status       string
	CreatedBy    uuid.UUID
}

// ===========================================================================
// Deliveries
// ===========================================================================
func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.TenantID,
		arg.SalesOrderID,
		arg.CustomerID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const createGoodsReceipt = `-- name: CreateGoodsReceipt :one

INSERT INTO goods_receipts (tenant_id, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, doc_number, status, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type CreateGoodsReceiptParams struct {
	TenantID        uuid.UUID
	PurchaseOrderID pgtype.UUID
	SupplierID      uuid.UUID
	WarehouseID     uuid.UUID
	DocDate         pgtype.Date
	Notes           string
	ReversesID      pgtype.UUID
	Status          string
	CreatedBy       uuid.UUID
}

// ===========================================================================
// Goods receipts
// ===========================================================================
func (q *Queries) CreateGoodsReceipt(ctx context.Context, arg CreateGoodsReceiptParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, createGoodsReceipt,
		arg.TenantID,
		arg.PurchaseOrderID,
		arg.SupplierID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one


INSERT INTO purchase_orders (tenant_id, supplier_id, warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, doc_number, status, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type CreatePurchaseOrderParams struct {
	TenantID    uuid.UUID
	SupplierID  uuid.UUID
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	ReversesID  pgtype.UUID
	Status      string
	CreatedBy   uuid.UUID
}

// Document queries (Track C - docs/plans/m1-parallel.md). Draft CRUD for the six
// document types plus the header transitions posting and reversal need. Movement
// writes, gapless numbering, and stock_levels are owned by the Poster (Track B);
// these queries only manage the document tables. Every query is tenant-scoped and
// runs under an app.tenant_id transaction so RLS applies (ADR-0004).
// ===========================================================================
// Purchase orders
// ===========================================================================
func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.TenantID,
		arg.SupplierID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const createSalesOrder = `-- name: CreateSalesOrder :one

INSERT INTO sales_orders (tenant_id, customer_id, warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, doc_number, status, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type CreateSalesOrderParams struct {
	TenantID    uuid.UUID
	CustomerID  uuid.UUID
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	ReversesID  pgtype.UUID
	Status      string
	CreatedBy   uuid.UUID
}

// ===========================================================================
// Sales orders
// ===========================================================================
func (q *Queries) CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, createSalesOrder,
		arg.TenantID,
		arg.CustomerID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const createStockAdjustment = `-- name: CreateStockAdjustment :one

INSERT INTO stock_adjustments (tenant_id, warehouse_id, reason, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, doc_number, status, warehouse_id, reason, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type CreateStockAdjustmentParams struct {
	TenantID    uuid.UUID
	WarehouseID uuid.UUID
	Reason      string
	DocDate     pgtype.Date
	Notes       string
	ReversesID  pgtype.UUID
	Status      string
	CreatedBy   uuid.UUID
}

// ===========================================================================
// Stock adjustments
// ===========================================================================
func (q *Queries) CreateStockAdjustment(ctx context.Context, arg CreateStockAdjustmentParams) (StockAdjustment, error) {
	row := q.db.QueryRow(ctx, createStockAdjustment,
		arg.TenantID,
		arg.WarehouseID,
		arg.Reason,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i StockAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.Reason,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const createStockOpname = `-- name: CreateStockOpname :one

INSERT INTO stock_opnames (tenant_id, warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, doc_number, status, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type CreateStockOpnameParams struct {
	TenantID    uuid.UUID
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	ReversesID  pgtype.UUID
	Status      string
	CreatedBy   uuid.UUID
}

// ===========================================================================
// Stock opnames
// ===========================================================================
func (q *Queries) CreateStockOpname(ctx context.Context, arg CreateStockOpnameParams) (StockOpname, error) {
	row := q.db.QueryRow(ctx, createStockOpname,
		arg.TenantID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i StockOpname
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const createStockTransfer = `-- name: CreateStockTransfer :one

INSERT INTO stock_transfers (tenant_id, from_warehouse_id, to_warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, doc_number, status, from_warehouse_id, to_warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type CreateStockTransferParams struct {
	TenantID        uuid.UUID
	FromWarehouseID uuid.UUID
	ToWarehouseID   uuid.UUID
	DocDate         pgtype.Date
	Notes           string
	ReversesID      pgtype.UUID
	Status          string
	CreatedBy       uuid.UUID
}

// ===========================================================================
// Stock transfers
// ===========================================================================
func (q *Queries) CreateStockTransfer(ctx context.Context, arg CreateStockTransferParams) (StockTransfer, error) {
	row := q.db.QueryRow(ctx, createStockTransfer,
		arg.TenantID,
		arg.FromWarehouseID,
		arg.ToWarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i StockTransfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const deleteDelivery = `-- name: DeleteDelivery :exec
DELETE FROM deliveries WHERE tenant_id = $1 AND id = $2
`

type DeleteDeliveryParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteDelivery(ctx context.Context, arg DeleteDeliveryParams) error {
	_, err := q.db.Exec(ctx, deleteDelivery, arg.TenantID, arg.ID)
	return err
}

const deleteDeliveryLines = `-- name: DeleteDeliveryLines :exec
DELETE FROM delivery_lines WHERE tenant_id = $1 AND delivery_id = $2
`

type DeleteDeliveryLinesParams struct {
	TenantID   uuid.UUID
	DeliveryID uuid.UUID
}

func (q *Queries) DeleteDeliveryLines(ctx context.Context, arg DeleteDeliveryLinesParams) error {
	_, err := q.db.Exec(ctx, deleteDeliveryLines, arg.TenantID, arg.DeliveryID)
	return err
}

const deleteGoodsReceipt = `-- name: DeleteGoodsReceipt :exec
DELETE FROM goods_receipts WHERE tenant_id = $1 AND id = $2
`

type DeleteGoodsReceiptParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteGoodsReceipt(ctx context.Context, arg DeleteGoodsReceiptParams) error {
	_, err := q.db.Exec(ctx, deleteGoodsReceipt, arg.TenantID, arg.ID)
	return err
}

const deleteGoodsReceiptLines = `-- name: DeleteGoodsReceiptLines :exec
DELETE FROM goods_receipt_lines WHERE tenant_id = $1 AND goods_receipt_id = $2
`

type DeleteGoodsReceiptLinesParams struct {
	TenantID       uuid.UUID
	GoodsReceiptID uuid.UUID
}

func (q *Queries) DeleteGoodsReceiptLines(ctx context.Context, arg DeleteGoodsReceiptLinesParams) error {
	_, err := q.db.Exec(ctx, deleteGoodsReceiptLines, arg.TenantID, arg.GoodsReceiptID)
	return err
}

const deletePurchaseOrder = `-- name: DeletePurchaseOrder :exec
DELETE FROM purchase_orders WHERE tenant_id = $1 AND id = $2
`

type DeletePurchaseOrderParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeletePurchaseOrder(ctx context.Context, arg DeletePurchaseOrderParams) error {
	_, err := q.db.Exec(ctx, deletePurchaseOrder, arg.TenantID, arg.ID)
	return err
}

const deletePurchaseOrderLines = `-- name: DeletePurchaseOrderLines :exec
DELETE FROM purchase_order_lines WHERE tenant_id = $1 AND purchase_order_id = $2
`

type DeletePurchaseOrderLinesParams struct {
	TenantID        uuid.UUID
	PurchaseOrderID uuid.UUID
}

func (q *Queries) DeletePurchaseOrderLines(ctx context.Context, arg DeletePurchaseOrderLinesParams) error {
	_, err := q.db.Exec(ctx, deletePurchaseOrderLines, arg.TenantID, arg.PurchaseOrderID)
	return err
}

const deleteSalesOrder = `-- name: DeleteSalesOrder :exec
DELETE FROM sales_orders WHERE tenant_id = $1 AND id = $2
`

type DeleteSalesOrderParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteSalesOrder(ctx context.Context, arg DeleteSalesOrderParams) error {
	_, err := q.db.Exec(ctx, deleteSalesOrder, arg.TenantID, arg.ID)
	return err
}

const deleteSalesOrderLines = `-- name: DeleteSalesOrderLines :exec
DELETE FROM sales_order_lines WHERE tenant_id = $1 AND sales_order_id = $2
`

type DeleteSalesOrderLinesParams struct {
	TenantID     uuid.UUID
	SalesOrderID uuid.UUID
}

func (q *Queries) DeleteSalesOrderLines(ctx context.Context, arg DeleteSalesOrderLinesParams) error {
	_, err := q.db.Exec(ctx, deleteSalesOrderLines, arg.TenantID, arg.SalesOrderID)
	return err
}

const deleteStockAdjustment = `-- name: DeleteStockAdjustment :exec
DELETE FROM stock_adjustments WHERE tenant_id = $1 AND id = $2
`

type DeleteStockAdjustmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteStockAdjustment(ctx context.Context, arg DeleteStockAdjustmentParams) error {
	_, err := q.db.Exec(ctx, deleteStockAdjustment, arg.TenantID, arg.ID)
	return err
}

const deleteStockAdjustmentLines = `-- name: DeleteStockAdjustmentLines :exec
DELETE FROM stock_adjustment_lines WHERE tenant_id = $1 AND stock_adjustment_id = $2
`

type DeleteStockAdjustmentLinesParams struct {
	TenantID          uuid.UUID
	StockAdjustmentID uuid.UUID
}

func (q *Queries) DeleteStockAdjustmentLines(ctx context.Context, arg DeleteStockAdjustmentLinesParams) error {
	_, err := q.db.Exec(ctx, deleteStockAdjustmentLines, arg.TenantID, arg.StockAdjustmentID)
	return err
}

const deleteStockOpname = `-- name: DeleteStockOpname :exec
DELETE FROM stock_opnames WHERE tenant_id = $1 AND id = $2
`

type DeleteStockOpnameParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteStockOpname(ctx context.Context, arg DeleteStockOpnameParams) error {
	_, err := q.db.Exec(ctx, deleteStockOpname, arg.TenantID, arg.ID)
	return err
}

const deleteStockOpnameLines = `-- name: DeleteStockOpnameLines :exec
DELETE FROM stock_opname_lines WHERE tenant_id = $1 AND stock_opname_id = $2
`

type DeleteStockOpnameLinesParams struct {
	TenantID      uuid.UUID
	StockOpnameID uuid.UUID
}

func (q *Queries) DeleteStockOpnameLines(ctx context.Context, arg DeleteStockOpnameLinesParams) error {
	_, err := q.db.Exec(ctx, deleteStockOpnameLines, arg.TenantID, arg.StockOpnameID)
	return err
}

const deleteStockTransfer = `-- name: DeleteStockTransfer :exec
DELETE FROM stock_transfers WHERE tenant_id = $1 AND id = $2
`

type DeleteStockTransferParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteStockTransfer(ctx context.Context, arg DeleteStockTransferParams) error {
	_, err := q.db.Exec(ctx, deleteStockTransfer, arg.TenantID, arg.ID)
	return err
}

const deleteStockTransferLines = `-- name: DeleteStockTransferLines :exec
DELETE FROM stock_transfer_lines WHERE tenant_id = $1 AND stock_transfer_id = $2
`

type DeleteStockTransferLinesParams struct {
	TenantID        uuid.UUID
	StockTransferID uuid.UUID
}

func (q *Queries) DeleteStockTransferLines(ctx context.Context, arg DeleteStockTransferLinesParams) error {
	_, err := q.db.Exec(ctx, deleteStockTransferLines, arg.TenantID, arg.StockTransferID)
	return err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, tenant_id, doc_number, status, sales_order_id, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM deliveries WHERE tenant_id = $1 AND id = $2
`

type GetDeliveryParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetDelivery(ctx context.Context, arg GetDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, arg.TenantID, arg.ID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const getGoodsReceipt = `-- name: GetGoodsReceipt :one
SELECT id, tenant_id, doc_number, status, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM goods_receipts WHERE tenant_id = $1 AND id = $2
`

type GetGoodsReceiptParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetGoodsReceipt(ctx context.Context, arg GetGoodsReceiptParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, getGoodsReceipt, arg.TenantID, arg.ID)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const getPOLineRollups = `-- name: GetPOLineRollups :many

SELECT pol.id,
       COALESCE(SUM(grl.qty), '0'::numeric) AS received_qty
FROM purchase_order_lines pol
LEFT JOIN goods_receipt_lines grl
    ON grl.purchase_order_line_id = pol.id
    AND grl.tenant_id = pol.tenant_id
LEFT JOIN goods_receipts gr
    ON gr.id = grl.goods_receipt_id
    AND gr.tenant_id = pol.tenant_id
    AND gr.status = 'posted'
    AND gr.reverses_id IS NULL
WHERE pol.tenant_id = $1
  AND pol.purchase_order_id = $2
GROUP BY pol.id, pol.line_no
ORDER BY pol.line_no
`

type GetPOLineRollupsParams struct {
	TenantID        uuid.UUID
	PurchaseOrderID uuid.UUID
}

type GetPOLineRollupsRow struct {
	ID          uuid.UUID
	ReceivedQty interface{}
}

// ===========================================================================
// Fulfillment rollup (ADR-0016): server-computed received/delivered qty
// ===========================================================================
// Sum of received qty per PO line from posted non-reversal goods receipts.
// Returns (id, received_qty) ordered by line_no.
func (q *Queries) GetPOLineRollups(ctx context.Context, arg GetPOLineRollupsParams) ([]GetPOLineRollupsRow, error) {
	rows, err := q.db.Query(ctx, getPOLineRollups, arg.TenantID, arg.PurchaseOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPOLineRollupsRow
	for rows.Next() {
		var i GetPOLineRollupsRow
		if err := rows.Scan(&i.ID, &i.ReceivedQty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT id, tenant_id, doc_number, status, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM purchase_orders WHERE tenant_id = $1 AND id = $2
`

type GetPurchaseOrderParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrder, arg.TenantID, arg.ID)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const getPurchaseOrderLineByID = `-- name: GetPurchaseOrderLineByID :one
SELECT id, tenant_id, purchase_order_id, line_no, product_id, uom, qty, unit_cost FROM purchase_order_lines WHERE tenant_id = $1 AND id = $2
`

type GetPurchaseOrderLineByIDParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetPurchaseOrderLineByID(ctx context.Context, arg GetPurchaseOrderLineByIDParams) (PurchaseOrderLine, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrderLineByID, arg.TenantID, arg.ID)
	var i PurchaseOrderLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PurchaseOrderID,
		&i.LineNo,
		&i.ProductID,
		&i.Uom,
		&i.Qty,
		&i.UnitCost,
	)
	return i, err
}

const getSOLineRollups = `-- name: GetSOLineRollups :many
SELECT sol.id,
       COALESCE(SUM(dl.qty), '0'::numeric) AS delivered_qty
FROM sales_order_lines sol
LEFT JOIN delivery_lines dl
    ON dl.sales_order_line_id = sol.id
    AND dl.tenant_id = sol.tenant_id
LEFT JOIN deliveries d
    ON d.id = dl.delivery_id
    AND d.tenant_id = sol.tenant_id
    AND d.status = 'posted'
    AND d.reverses_id IS NULL
WHERE sol.tenant_id = $1
  AND sol.sales_order_id = $2
GROUP BY sol.id, sol.line_no
ORDER BY sol.line_no
`

type GetSOLineRollupsParams struct {
	TenantID     uuid.UUID
	SalesOrderID uuid.UUID
}

type GetSOLineRollupsRow struct {
	ID           uuid.UUID
	DeliveredQty interface{}
}

// Sum of delivered qty per SO line from posted non-reversal deliveries.
func (q *Queries) GetSOLineRollups(ctx context.Context, arg GetSOLineRollupsParams) ([]GetSOLineRollupsRow, error) {
	rows, err := q.db.Query(ctx, getSOLineRollups, arg.TenantID, arg.SalesOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSOLineRollupsRow
	for rows.Next() {
		var i GetSOLineRollupsRow
		if err := rows.Scan(&i.ID, &i.DeliveredQty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesOrder = `-- name: GetSalesOrder :one
SELECT id, tenant_id, doc_number, status, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM sales_orders WHERE tenant_id = $1 AND id = $2
`

type GetSalesOrderParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetSalesOrder(ctx context.Context, arg GetSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrder, arg.TenantID, arg.ID)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const getSalesOrderLineByID = `-- name: GetSalesOrderLineByID :one
SELECT id, tenant_id, sales_order_id, line_no, product_id, uom, qty, unit_price FROM sales_order_lines WHERE tenant_id = $1 AND id = $2
`

type GetSalesOrderLineByIDParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetSalesOrderLineByID(ctx context.Context, arg GetSalesOrderLineByIDParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, getSalesOrderLineByID, arg.TenantID, arg.ID)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.LineNo,
		&i.ProductID,
		&i.Uom,
		&i.Qty,
		&i.UnitPrice,
	)
	return i, err
}

const getStockAdjustment = `-- name: GetStockAdjustment :one
SELECT id, tenant_id, doc_number, status, warehouse_id, reason, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM stock_adjustments WHERE tenant_id = $1 AND id = $2
`

type GetStockAdjustmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetStockAdjustment(ctx context.Context, arg GetStockAdjustmentParams) (StockAdjustment, error) {
	row := q.db.QueryRow(ctx, getStockAdjustment, arg.TenantID, arg.ID)
	var i StockAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.Reason,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const getStockLevelForDoc = `-- name: GetStockLevelForDoc :one

SELECT qty_on_hand, avg_cost
FROM stock_levels
WHERE tenant_id = $1
  AND product_id = $2
  AND warehouse_id = $3
  AND batch_id IS NOT DISTINCT FROM $4
`

type GetStockLevelForDocParams struct {
	TenantID    uuid.UUID
	ProductID   uuid.UUID
	WarehouseID uuid.UUID
	BatchID     pgtype.UUID
}

type GetStockLevelForDocRow struct {
	QtyOnHand pgtype.Numeric
	AvgCost   pgtype.Numeric
}

// ===========================================================================
// Shared: current stock level for opname variance (read the derived cache)
// ===========================================================================
func (q *Queries) GetStockLevelForDoc(ctx context.Context, arg GetStockLevelForDocParams) (GetStockLevelForDocRow, error) {
	row := q.db.QueryRow(ctx, getStockLevelForDoc,
		arg.TenantID,
		arg.ProductID,
		arg.WarehouseID,
		arg.BatchID,
	)
	var i GetStockLevelForDocRow
	err := row.Scan(&i.QtyOnHand, &i.AvgCost)
	return i, err
}

const getStockOpname = `-- name: GetStockOpname :one
SELECT id, tenant_id, doc_number, status, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM stock_opnames WHERE tenant_id = $1 AND id = $2
`

type GetStockOpnameParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetStockOpname(ctx context.Context, arg GetStockOpnameParams) (StockOpname, error) {
	row := q.db.QueryRow(ctx, getStockOpname, arg.TenantID, arg.ID)
	var i StockOpname
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const getStockTransfer = `-- name: GetStockTransfer :one
SELECT id, tenant_id, doc_number, status, from_warehouse_id, to_warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM stock_transfers WHERE tenant_id = $1 AND id = $2
`

type GetStockTransferParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetStockTransfer(ctx context.Context, arg GetStockTransferParams) (StockTransfer, error) {
	row := q.db.QueryRow(ctx, getStockTransfer, arg.TenantID, arg.ID)
	var i StockTransfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const getTenantToleranceOverReceipt = `-- name: GetTenantToleranceOverReceipt :one
SELECT COALESCE(
    (SELECT tolerance_over_receipt FROM tenant_settings WHERE tenant_id = $1),
    '0'::numeric
) AS tolerance
`

// Tenant over-receipt tolerance (default 0 when no settings row exists).
func (q *Queries) GetTenantToleranceOverReceipt(ctx context.Context, tenantID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTenantToleranceOverReceipt, tenantID)
	var tolerance interface{}
	err := row.Scan(&tolerance)
	return tolerance, err
}

const insertDeliveryLine = `-- name: InsertDeliveryLine :one
INSERT INTO delivery_lines (tenant_id, delivery_id, line_no, sales_order_line_id, product_id, batch_id, uom, qty)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, delivery_id, line_no, sales_order_line_id, product_id, batch_id, uom, qty
`

type InsertDeliveryLineParams struct {
	TenantID         uuid.UUID
	DeliveryID       uuid.UUID
	LineNo           int32
	SalesOrderLineID pgtype.UUID
	ProductID        uuid.UUID
	BatchID          pgtype.UUID
	Uom              string
	Qty              pgtype.Numeric
}

func (q *Queries) InsertDeliveryLine(ctx context.Context, arg InsertDeliveryLineParams) (DeliveryLine, error) {
	row := q.db.QueryRow(ctx, insertDeliveryLine,
		arg.TenantID,
		arg.DeliveryID,
		arg.LineNo,
		arg.SalesOrderLineID,
		arg.ProductID,
		arg.BatchID,
		arg.Uom,
		arg.Qty,
	)
	var i DeliveryLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeliveryID,
		&i.LineNo,
		&i.SalesOrderLineID,
		&i.ProductID,
		&i.BatchID,
		&i.Uom,
		&i.Qty,
	)
	return i, err
}

const insertGoodsReceiptLine = `-- name: InsertGoodsReceiptLine :one
INSERT INTO goods_receipt_lines (tenant_id, goods_receipt_id, line_no, purchase_order_line_id, product_id, batch_id, uom, qty, unit_cost)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, goods_receipt_id, line_no, purchase_order_line_id, product_id, batch_id, uom, qty, unit_cost
`

type InsertGoodsReceiptLineParams struct {
	TenantID            uuid.UUID
	GoodsReceiptID      uuid.UUID
	LineNo              int32
	PurchaseOrderLineID pgtype.UUID
	ProductID           uuid.UUID
	BatchID             pgtype.UUID
	Uom                 string
	Qty                 pgtype.Numeric
	UnitCost            pgtype.Numeric
}

func (q *Queries) InsertGoodsReceiptLine(ctx context.Context, arg InsertGoodsReceiptLineParams) (GoodsReceiptLine, error) {
	row := q.db.QueryRow(ctx, insertGoodsReceiptLine,
		arg.TenantID,
		arg.GoodsReceiptID,
		arg.LineNo,
		arg.PurchaseOrderLineID,
		arg.ProductID,
		arg.BatchID,
		arg.Uom,
		arg.Qty,
		arg.UnitCost,
	)
	var i GoodsReceiptLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GoodsReceiptID,
		&i.LineNo,
		&i.PurchaseOrderLineID,
		&i.ProductID,
		&i.BatchID,
		&i.Uom,
		&i.Qty,
		&i.UnitCost,
	)
	return i, err
}

const insertGoodsReceiptLineCostOverride = `-- name: InsertGoodsReceiptLineCostOverride :exec
INSERT INTO goods_receipt_line_cost_overrides
    (tenant_id, goods_receipt_line_id, po_line_unit_cost, override_unit_cost, actor_user_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertGoodsReceiptLineCostOverrideParams struct {
	TenantID           uuid.UUID
	GoodsReceiptLineID uuid.UUID
	PoLineUnitCost     pgtype.Numeric
	OverrideUnitCost   pgtype.Numeric
	ActorUserID        uuid.UUID
}

func (q *Queries) InsertGoodsReceiptLineCostOverride(ctx context.Context, arg InsertGoodsReceiptLineCostOverrideParams) error {
	_, err := q.db.Exec(ctx, insertGoodsReceiptLineCostOverride,
		arg.TenantID,
		arg.GoodsReceiptLineID,
		arg.PoLineUnitCost,
		arg.OverrideUnitCost,
		arg.ActorUserID,
	)
	return err
}

const insertPurchaseOrderLine = `-- name: InsertPurchaseOrderLine :one
INSERT INTO purchase_order_lines (tenant_id, purchase_order_id, line_no, product_id, uom, qty, unit_cost)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, purchase_order_id, line_no, product_id, uom, qty, unit_cost
`

type InsertPurchaseOrderLineParams struct {
	TenantID        uuid.UUID
	PurchaseOrderID uuid.UUID
	LineNo          int32
	ProductID       uuid.UUID
	Uom             string
	Qty             pgtype.Numeric
	UnitCost        pgtype.Numeric
}

func (q *Queries) InsertPurchaseOrderLine(ctx context.Context, arg InsertPurchaseOrderLineParams) (PurchaseOrderLine, error) {
	row := q.db.QueryRow(ctx, insertPurchaseOrderLine,
		arg.TenantID,
		arg.PurchaseOrderID,
		arg.LineNo,
		arg.ProductID,
		arg.Uom,
		arg.Qty,
		arg.UnitCost,
	)
	var i PurchaseOrderLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PurchaseOrderID,
		&i.LineNo,
		&i.ProductID,
		&i.Uom,
		&i.Qty,
		&i.UnitCost,
	)
	return i, err
}

const insertSalesOrderLine = `-- name: InsertSalesOrderLine :one
INSERT INTO sales_order_lines (tenant_id, sales_order_id, line_no, product_id, uom, qty, unit_price)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, sales_order_id, line_no, product_id, uom, qty, unit_price
`

type InsertSalesOrderLineParams struct {
	TenantID     uuid.UUID
	SalesOrderID uuid.UUID
	LineNo       int32
	ProductID    uuid.UUID
	Uom          string
	Qty          pgtype.Numeric
	UnitPrice    pgtype.Numeric
}

func (q *Queries) InsertSalesOrderLine(ctx context.Context, arg InsertSalesOrderLineParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, insertSalesOrderLine,
		arg.TenantID,
		arg.SalesOrderID,
		arg.LineNo,
		arg.ProductID,
		arg.Uom,
		arg.Qty,
		arg.UnitPrice,
	)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.LineNo,
		&i.ProductID,
		&i.Uom,
		&i.Qty,
		&i.UnitPrice,
	)
	return i, err
}

const insertStockAdjustmentLine = `-- name: InsertStockAdjustmentLine :one
INSERT INTO stock_adjustment_lines (tenant_id, stock_adjustment_id, line_no, product_id, batch_id, uom, qty, unit_cost)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, stock_adjustment_id, line_no, product_id, batch_id, uom, qty, unit_cost
`

type InsertStockAdjustmentLineParams struct {
	TenantID          uuid.UUID
	StockAdjustmentID uuid.UUID
	LineNo            int32
	ProductID         uuid.UUID
	BatchID           pgtype.UUID
	Uom               string
	Qty               pgtype.Numeric
	UnitCost          pgtype.Numeric
}

func (q *Queries) InsertStockAdjustmentLine(ctx context.Context, arg InsertStockAdjustmentLineParams) (StockAdjustmentLine, error) {
	row := q.db.QueryRow(ctx, insertStockAdjustmentLine,
		arg.TenantID,
		arg.StockAdjustmentID,
		arg.LineNo,
		arg.ProductID,
		arg.BatchID,
		arg.Uom,
		arg.Qty,
		arg.UnitCost,
	)
	var i StockAdjustmentLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StockAdjustmentID,
		&i.LineNo,
		&i.ProductID,
		&i.BatchID,
		&i.Uom,
		&i.Qty,
		&i.UnitCost,
	)
	return i, err
}

const insertStockOpnameLine = `-- name: InsertStockOpnameLine :one
INSERT INTO stock_opname_lines (tenant_id, stock_opname_id, line_no, product_id, batch_id, uom, counted_qty)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, stock_opname_id, line_no, product_id, batch_id, uom, counted_qty, system_qty
`

type InsertStockOpnameLineParams struct {
	TenantID      uuid.UUID
	StockOpnameID uuid.UUID
	LineNo        int32
	ProductID     uuid.UUID
	BatchID       pgtype.UUID
	Uom           string
	CountedQty    pgtype.Numeric
}

func (q *Queries) InsertStockOpnameLine(ctx context.Context, arg InsertStockOpnameLineParams) (StockOpnameLine, error) {
	row := q.db.QueryRow(ctx, insertStockOpnameLine,
		arg.TenantID,
		arg.StockOpnameID,
		arg.LineNo,
		arg.ProductID,
		arg.BatchID,
		arg.Uom,
		arg.CountedQty,
	)
	var i StockOpnameLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StockOpnameID,
		&i.LineNo,
		&i.ProductID,
		&i.BatchID,
		&i.Uom,
		&i.CountedQty,
		&i.SystemQty,
	)
	return i, err
}

const insertStockTransferLine = `-- name: InsertStockTransferLine :one
INSERT INTO stock_transfer_lines (tenant_id, stock_transfer_id, line_no, product_id, batch_id, uom, qty)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, stock_transfer_id, line_no, product_id, batch_id, uom, qty
`

type InsertStockTransferLineParams struct {
	TenantID        uuid.UUID
	StockTransferID uuid.UUID
	LineNo          int32
	ProductID       uuid.UUID
	BatchID         pgtype.UUID
	Uom             string
	Qty             pgtype.Numeric
}

func (q *Queries) InsertStockTransferLine(ctx context.Context, arg InsertStockTransferLineParams) (StockTransferLine, error) {
	row := q.db.QueryRow(ctx, insertStockTransferLine,
		arg.TenantID,
		arg.StockTransferID,
		arg.LineNo,
		arg.ProductID,
		arg.BatchID,
		arg.Uom,
		arg.Qty,
	)
	var i StockTransferLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StockTransferID,
		&i.LineNo,
		&i.ProductID,
		&i.BatchID,
		&i.Uom,
		&i.Qty,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, tenant_id, doc_number, status, sales_order_id, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM deliveries
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::uuid IS NULL OR warehouse_id = $3::uuid)
  AND ($4::date IS NULL OR doc_date >= $4::date)
  AND ($5::date IS NULL OR doc_date <= $5::date)
  AND ($6::text IS NULL OR doc_number ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL
       OR created_at < $7::timestamptz
       OR (created_at = $7::timestamptz AND id < $8::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListDeliveriesParams struct {
	TenantID          uuid.UUID
	FilterStatus      pgtype.Text
	FilterWarehouseID pgtype.UUID
	FilterDateFrom    pgtype.Date
	FilterDateTo      pgtype.Date
	FilterQ           pgtype.Text
	CursorTs          pgtype.Timestamptz
	CursorID          pgtype.UUID
	PageLimit         int32
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries,
		arg.TenantID,
		arg.FilterStatus,
		arg.FilterWarehouseID,
		arg.FilterDateFrom,
		arg.FilterDateTo,
		arg.FilterQ,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.SalesOrderID,
			&i.CustomerID,
			&i.WarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
			&i.PostedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryLines = `-- name: ListDeliveryLines :many
SELECT id, tenant_id, delivery_id, line_no, sales_order_line_id, product_id, batch_id, uom, qty FROM delivery_lines WHERE tenant_id = $1 AND delivery_id = $2 ORDER BY line_no
`

type ListDeliveryLinesParams struct {
	TenantID   uuid.UUID
	DeliveryID uuid.UUID
}

func (q *Queries) ListDeliveryLines(ctx context.Context, arg ListDeliveryLinesParams) ([]DeliveryLine, error) {
	rows, err := q.db.Query(ctx, listDeliveryLines, arg.TenantID, arg.DeliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryLine
	for rows.Next() {
		var i DeliveryLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DeliveryID,
			&i.LineNo,
			&i.SalesOrderLineID,
			&i.ProductID,
			&i.BatchID,
			&i.Uom,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoodsReceiptLines = `-- name: ListGoodsReceiptLines :many
SELECT id, tenant_id, goods_receipt_id, line_no, purchase_order_line_id, product_id, batch_id, uom, qty, unit_cost FROM goods_receipt_lines WHERE tenant_id = $1 AND goods_receipt_id = $2 ORDER BY line_no
`

type ListGoodsReceiptLinesParams struct {
	TenantID       uuid.UUID
	GoodsReceiptID uuid.UUID
}

func (q *Queries) ListGoodsReceiptLines(ctx context.Context, arg ListGoodsReceiptLinesParams) ([]GoodsReceiptLine, error) {
	rows, err := q.db.Query(ctx, listGoodsReceiptLines, arg.TenantID, arg.GoodsReceiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsReceiptLine
	for rows.Next() {
		var i GoodsReceiptLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.GoodsReceiptID,
			&i.LineNo,
			&i.PurchaseOrderLineID,
			&i.ProductID,
			&i.BatchID,
			&i.Uom,
			&i.Qty,
			&i.UnitCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoodsReceipts = `-- name: ListGoodsReceipts :many
SELECT id, tenant_id, doc_number, status, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM goods_receipts
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::uuid IS NULL OR warehouse_id = $3::uuid)
  AND ($4::date IS NULL OR doc_date >= $4::date)
  AND ($5::date IS NULL OR doc_date <= $5::date)
  AND ($6::text IS NULL OR doc_number ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL
       OR created_at < $7::timestamptz
       OR (created_at = $7::timestamptz AND id < $8::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListGoodsReceiptsParams struct {
	TenantID          uuid.UUID
	FilterStatus      pgtype.Text
	FilterWarehouseID pgtype.UUID
	FilterDateFrom    pgtype.Date
	FilterDateTo      pgtype.Date
	FilterQ           pgtype.Text
	CursorTs          pgtype.Timestamptz
	CursorID          pgtype.UUID
	PageLimit         int32
}

func (q *Queries) ListGoodsReceipts(ctx context.Context, arg ListGoodsReceiptsParams) ([]GoodsReceipt, error) {
	rows, err := q.db.Query(ctx, listGoodsReceipts,
		arg.TenantID,
		arg.FilterStatus,
		arg.FilterWarehouseID,
		arg.FilterDateFrom,
		arg.FilterDateTo,
		arg.FilterQ,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsReceipt
	for rows.Next() {
		var i GoodsReceipt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.PurchaseOrderID,
			&i.SupplierID,
			&i.WarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
			&i.PostedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrderLines = `-- name: ListPurchaseOrderLines :many
SELECT id, tenant_id, purchase_order_id, line_no, product_id, uom, qty, unit_cost FROM purchase_order_lines WHERE tenant_id = $1 AND purchase_order_id = $2 ORDER BY line_no
`

type ListPurchaseOrderLinesParams struct {
	TenantID        uuid.UUID
	PurchaseOrderID uuid.UUID
}

func (q *Queries) ListPurchaseOrderLines(ctx context.Context, arg ListPurchaseOrderLinesParams) ([]PurchaseOrderLine, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderLines, arg.TenantID, arg.PurchaseOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrderLine
	for rows.Next() {
		var i PurchaseOrderLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PurchaseOrderID,
			&i.LineNo,
			&i.ProductID,
			&i.Uom,
			&i.Qty,
			&i.UnitCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT id, tenant_id, doc_number, status, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM purchase_orders
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::uuid IS NULL OR warehouse_id = $3::uuid)
  AND ($4::date IS NULL OR doc_date >= $4::date)
  AND ($5::date IS NULL OR doc_date <= $5::date)
  AND ($6::text IS NULL OR doc_number ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL
       OR created_at < $7::timestamptz
       OR (created_at = $7::timestamptz AND id < $8::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListPurchaseOrdersParams struct {
	TenantID          uuid.UUID
	FilterStatus      pgtype.Text
	FilterWarehouseID pgtype.UUID
	FilterDateFrom    pgtype.Date
	FilterDateTo      pgtype.Date
	FilterQ           pgtype.Text
	CursorTs          pgtype.Timestamptz
	CursorID          pgtype.UUID
	PageLimit         int32
}

func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]PurchaseOrder, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders,
		arg.TenantID,
		arg.FilterStatus,
		arg.FilterWarehouseID,
		arg.FilterDateFrom,
		arg.FilterDateTo,
		arg.FilterQ,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrder
	for rows.Next() {
		var i PurchaseOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.SupplierID,
			&i.WarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
			&i.PostedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrderLines = `-- name: ListSalesOrderLines :many
SELECT id, tenant_id, sales_order_id, line_no, product_id, uom, qty, unit_price FROM sales_order_lines WHERE tenant_id = $1 AND sales_order_id = $2 ORDER BY line_no
`

type ListSalesOrderLinesParams struct {
	TenantID     uuid.UUID
	SalesOrderID uuid.UUID
}

func (q *Queries) ListSalesOrderLines(ctx context.Context, arg ListSalesOrderLinesParams) ([]SalesOrderLine, error) {
	rows, err := q.db.Query(ctx, listSalesOrderLines, arg.TenantID, arg.SalesOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesOrderLine
	for rows.Next() {
		var i SalesOrderLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SalesOrderID,
			&i.LineNo,
			&i.ProductID,
			&i.Uom,
			&i.Qty,
			&i.UnitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrders = `-- name: ListSalesOrders :many
SELECT id, tenant_id, doc_number, status, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM sales_orders
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::uuid IS NULL OR warehouse_id = $3::uuid)
  AND ($4::date IS NULL OR doc_date >= $4::date)
  AND ($5::date IS NULL OR doc_date <= $5::date)
  AND ($6::text IS NULL OR doc_number ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL
       OR created_at < $7::timestamptz
       OR (created_at = $7::timestamptz AND id < $8::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListSalesOrdersParams struct {
	TenantID          uuid.UUID
	FilterStatus      pgtype.Text
	FilterWarehouseID pgtype.UUID
	FilterDateFrom    pgtype.Date
	FilterDateTo      pgtype.Date
	FilterQ           pgtype.Text
	CursorTs          pgtype.Timestamptz
	CursorID          pgtype.UUID
	PageLimit         int32
}

func (q *Queries) ListSalesOrders(ctx context.Context, arg ListSalesOrdersParams) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, listSalesOrders,
		arg.TenantID,
		arg.FilterStatus,
		arg.FilterWarehouseID,
		arg.FilterDateFrom,
		arg.FilterDateTo,
		arg.FilterQ,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesOrder
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.CustomerID,
			&i.WarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
			&i.PostedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockAdjustmentLines = `-- name: ListStockAdjustmentLines :many
SELECT id, tenant_id, stock_adjustment_id, line_no, product_id, batch_id, uom, qty, unit_cost FROM stock_adjustment_lines WHERE tenant_id = $1 AND stock_adjustment_id = $2 ORDER BY line_no
`

type ListStockAdjustmentLinesParams struct {
	TenantID          uuid.UUID
	StockAdjustmentID uuid.UUID
}

func (q *Queries) ListStockAdjustmentLines(ctx context.Context, arg ListStockAdjustmentLinesParams) ([]StockAdjustmentLine, error) {
	rows, err := q.db.Query(ctx, listStockAdjustmentLines, arg.TenantID, arg.StockAdjustmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockAdjustmentLine
	for rows.Next() {
		var i StockAdjustmentLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StockAdjustmentID,
			&i.LineNo,
			&i.ProductID,
			&i.BatchID,
			&i.Uom,
			&i.Qty,
			&i.UnitCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockAdjustments = `-- name: ListStockAdjustments :many
SELECT id, tenant_id, doc_number, status, warehouse_id, reason, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM stock_adjustments
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::uuid IS NULL OR warehouse_id = $3::uuid)
  AND ($4::date IS NULL OR doc_date >= $4::date)
  AND ($5::date IS NULL OR doc_date <= $5::date)
  AND ($6::text IS NULL OR doc_number ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL
       OR created_at < $7::timestamptz
       OR (created_at = $7::timestamptz AND id < $8::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListStockAdjustmentsParams struct {
	TenantID          uuid.UUID
	FilterStatus      pgtype.Text
	FilterWarehouseID pgtype.UUID
	FilterDateFrom    pgtype.Date
	FilterDateTo      pgtype.Date
	FilterQ           pgtype.Text
	CursorTs          pgtype.Timestamptz
	CursorID          pgtype.UUID
	PageLimit         int32
}

func (q *Queries) ListStockAdjustments(ctx context.Context, arg ListStockAdjustmentsParams) ([]StockAdjustment, error) {
	rows, err := q.db.Query(ctx, listStockAdjustments,
		arg.TenantID,
		arg.FilterStatus,
		arg.FilterWarehouseID,
		arg.FilterDateFrom,
		arg.FilterDateTo,
		arg.FilterQ,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockAdjustment
	for rows.Next() {
		var i StockAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.WarehouseID,
			&i.Reason,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
			&i.PostedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockOpnameLines = `-- name: ListStockOpnameLines :many
SELECT id, tenant_id, stock_opname_id, line_no, product_id, batch_id, uom, counted_qty, system_qty FROM stock_opname_lines WHERE tenant_id = $1 AND stock_opname_id = $2 ORDER BY line_no
`

type ListStockOpnameLinesParams struct {
	TenantID      uuid.UUID
	StockOpnameID uuid.UUID
}

func (q *Queries) ListStockOpnameLines(ctx context.Context, arg ListStockOpnameLinesParams) ([]StockOpnameLine, error) {
	rows, err := q.db.Query(ctx, listStockOpnameLines, arg.TenantID, arg.StockOpnameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockOpnameLine
	for rows.Next() {
		var i StockOpnameLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StockOpnameID,
			&i.LineNo,
			&i.ProductID,
			&i.BatchID,
			&i.Uom,
			&i.CountedQty,
			&i.SystemQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockOpnames = `-- name: ListStockOpnames :many
SELECT id, tenant_id, doc_number, status, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM stock_opnames
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::uuid IS NULL OR warehouse_id = $3::uuid)
  AND ($4::date IS NULL OR doc_date >= $4::date)
  AND ($5::date IS NULL OR doc_date <= $5::date)
  AND ($6::text IS NULL OR doc_number ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL
       OR created_at < $7::timestamptz
       OR (created_at = $7::timestamptz AND id < $8::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListStockOpnamesParams struct {
	TenantID          uuid.UUID
	FilterStatus      pgtype.Text
	FilterWarehouseID pgtype.UUID
	FilterDateFrom    pgtype.Date
	FilterDateTo      pgtype.Date
	FilterQ           pgtype.Text
	CursorTs          pgtype.Timestamptz
	CursorID          pgtype.UUID
	PageLimit         int32
}

func (q *Queries) ListStockOpnames(ctx context.Context, arg ListStockOpnamesParams) ([]StockOpname, error) {
	rows, err := q.db.Query(ctx, listStockOpnames,
		arg.TenantID,
		arg.FilterStatus,
		arg.FilterWarehouseID,
		arg.FilterDateFrom,
		arg.FilterDateTo,
		arg.FilterQ,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockOpname
	for rows.Next() {
		var i StockOpname
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.WarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
			&i.PostedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockTransferLines = `-- name: ListStockTransferLines :many
SELECT id, tenant_id, stock_transfer_id, line_no, product_id, batch_id, uom, qty FROM stock_transfer_lines WHERE tenant_id = $1 AND stock_transfer_id = $2 ORDER BY line_no
`

type ListStockTransferLinesParams struct {
	TenantID        uuid.UUID
	StockTransferID uuid.UUID
}

func (q *Queries) ListStockTransferLines(ctx context.Context, arg ListStockTransferLinesParams) ([]StockTransferLine, error) {
	rows, err := q.db.Query(ctx, listStockTransferLines, arg.TenantID, arg.StockTransferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockTransferLine
	for rows.Next() {
		var i StockTransferLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StockTransferID,
			&i.LineNo,
			&i.ProductID,
			&i.BatchID,
			&i.Uom,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockTransfers = `-- name: ListStockTransfers :many
SELECT id, tenant_id, doc_number, status, from_warehouse_id, to_warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by FROM stock_transfers
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::uuid IS NULL
       OR from_warehouse_id = $3::uuid
       OR to_warehouse_id   = $3::uuid)
  AND ($4::date IS NULL OR doc_date >= $4::date)
  AND ($5::date IS NULL OR doc_date <= $5::date)
  AND ($6::text IS NULL OR doc_number ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL
       OR created_at < $7::timestamptz
       OR (created_at = $7::timestamptz AND id < $8::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListStockTransfersParams struct {
	TenantID          uuid.UUID
	FilterStatus      pgtype.Text
	FilterWarehouseID pgtype.UUID
	FilterDateFrom    pgtype.Date
	FilterDateTo      pgtype.Date
	FilterQ           pgtype.Text
	CursorTs          pgtype.Timestamptz
	CursorID          pgtype.UUID
	PageLimit         int32
}

func (q *Queries) ListStockTransfers(ctx context.Context, arg ListStockTransfersParams) ([]StockTransfer, error) {
	rows, err := q.db.Query(ctx, listStockTransfers,
		arg.TenantID,
		arg.FilterStatus,
		arg.FilterWarehouseID,
		arg.FilterDateFrom,
		arg.FilterDateTo,
		arg.FilterQ,
		arg.CursorTs,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockTransfer
	for rows.Next() {
		var i StockTransfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.FromWarehouseID,
			&i.ToWarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
			&i.PostedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPOLineForReceipt = `-- name: LockPOLineForReceipt :exec
SELECT pg_advisory_xact_lock(
    ('x' || right(replace($1::text, '-', ''), 16))::bit(64)::bigint
)
`

// Advisory lock on a PO line (transaction-scoped) to serialize concurrent receipts.
func (q *Queries) LockPOLineForReceipt(ctx context.Context, purchaseOrderLineID string) error {
	_, err := q.db.Exec(ctx, lockPOLineForReceipt, purchaseOrderLineID)
	return err
}

const lockSOLineForDelivery = `-- name: LockSOLineForDelivery :exec
SELECT pg_advisory_xact_lock(
    ('x' || right(replace($1::text, '-', ''), 16))::bit(64)::bigint
)
`

// Advisory lock on an SO line (transaction-scoped) to serialize concurrent deliveries.
func (q *Queries) LockSOLineForDelivery(ctx context.Context, salesOrderLineID string) error {
	_, err := q.db.Exec(ctx, lockSOLineForDelivery, salesOrderLineID)
	return err
}

const markDeliveryPosted = `-- name: MarkDeliveryPosted :one
UPDATE deliveries
SET status = 'posted', doc_number = $1, posted_at = now(), posted_by = $2
WHERE tenant_id = $3 AND id = $4
RETURNING id, tenant_id, doc_number, status, sales_order_id, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type MarkDeliveryPostedParams struct {
	DocNumber pgtype.Text
	PostedBy  pgtype.UUID
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkDeliveryPosted(ctx context.Context, arg MarkDeliveryPostedParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, markDeliveryPosted,
		arg.DocNumber,
		arg.PostedBy,
		arg.TenantID,
		arg.ID,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const markDeliveryReversed = `-- name: MarkDeliveryReversed :exec
UPDATE deliveries
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkDeliveryReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkDeliveryReversed(ctx context.Context, arg MarkDeliveryReversedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markGoodsReceiptPosted = `-- name: MarkGoodsReceiptPosted :one
UPDATE goods_receipts
SET status = 'posted', doc_number = $1, posted_at = now(), posted_by = $2
WHERE tenant_id = $3 AND id = $4
RETURNING id, tenant_id, doc_number, status, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type MarkGoodsReceiptPostedParams struct {
	DocNumber pgtype.Text
	PostedBy  pgtype.UUID
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkGoodsReceiptPosted(ctx context.Context, arg MarkGoodsReceiptPostedParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, markGoodsReceiptPosted,
		arg.DocNumber,
		arg.PostedBy,
		arg.TenantID,
		arg.ID,
	)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const markGoodsReceiptReversed = `-- name: MarkGoodsReceiptReversed :exec
UPDATE goods_receipts
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkGoodsReceiptReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkGoodsReceiptReversed(ctx context.Context, arg MarkGoodsReceiptReversedParams) error {
	_, err := q.db.Exec(ctx, markGoodsReceiptReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markPurchaseOrderPosted = `-- name: MarkPurchaseOrderPosted :one
UPDATE purchase_orders
SET status = 'posted', doc_number = $1, posted_at = now(), posted_by = $2
WHERE tenant_id = $3 AND id = $4
RETURNING id, tenant_id, doc_number, status, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type MarkPurchaseOrderPostedParams struct {
	DocNumber pgtype.Text
	PostedBy  pgtype.UUID
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkPurchaseOrderPosted(ctx context.Context, arg MarkPurchaseOrderPostedParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, markPurchaseOrderPosted,
		arg.DocNumber,
		arg.PostedBy,
		arg.TenantID,
		arg.ID,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const markPurchaseOrderReversed = `-- name: MarkPurchaseOrderReversed :exec
UPDATE purchase_orders
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkPurchaseOrderReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkPurchaseOrderReversed(ctx context.Context, arg MarkPurchaseOrderReversedParams) error {
	_, err := q.db.Exec(ctx, markPurchaseOrderReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markSalesOrderPosted = `-- name: MarkSalesOrderPosted :one
UPDATE sales_orders
SET status = 'posted', doc_number = $1, posted_at = now(), posted_by = $2
WHERE tenant_id = $3 AND id = $4
RETURNING id, tenant_id, doc_number, status, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type MarkSalesOrderPostedParams struct {
	DocNumber pgtype.Text
	PostedBy  pgtype.UUID
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkSalesOrderPosted(ctx context.Context, arg MarkSalesOrderPostedParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, markSalesOrderPosted,
		arg.DocNumber,
		arg.PostedBy,
		arg.TenantID,
		arg.ID,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const markSalesOrderReversed = `-- name: MarkSalesOrderReversed :exec
UPDATE sales_orders
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkSalesOrderReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkSalesOrderReversed(ctx context.Context, arg MarkSalesOrderReversedParams) error {
	_, err := q.db.Exec(ctx, markSalesOrderReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markStockAdjustmentPosted = `-- name: MarkStockAdjustmentPosted :one
UPDATE stock_adjustments
SET status = 'posted', doc_number = $1, posted_at = now(), posted_by = $2
WHERE tenant_id = $3 AND id = $4
RETURNING id, tenant_id, doc_number, status, warehouse_id, reason, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type MarkStockAdjustmentPostedParams struct {
	DocNumber pgtype.Text
	PostedBy  pgtype.UUID
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkStockAdjustmentPosted(ctx context.Context, arg MarkStockAdjustmentPostedParams) (StockAdjustment, error) {
	row := q.db.QueryRow(ctx, markStockAdjustmentPosted,
		arg.DocNumber,
		arg.PostedBy,
		arg.TenantID,
		arg.ID,
	)
	var i StockAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.Reason,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const markStockAdjustmentReversed = `-- name: MarkStockAdjustmentReversed :exec
UPDATE stock_adjustments
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkStockAdjustmentReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkStockAdjustmentReversed(ctx context.Context, arg MarkStockAdjustmentReversedParams) error {
	_, err := q.db.Exec(ctx, markStockAdjustmentReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markStockOpnamePosted = `-- name: MarkStockOpnamePosted :one
UPDATE stock_opnames
SET status = 'posted', doc_number = $1, posted_at = now(), posted_by = $2
WHERE tenant_id = $3 AND id = $4
RETURNING id, tenant_id, doc_number, status, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type MarkStockOpnamePostedParams struct {
	DocNumber pgtype.Text
	PostedBy  pgtype.UUID
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkStockOpnamePosted(ctx context.Context, arg MarkStockOpnamePostedParams) (StockOpname, error) {
	row := q.db.QueryRow(ctx, markStockOpnamePosted,
		arg.DocNumber,
		arg.PostedBy,
		arg.TenantID,
		arg.ID,
	)
	var i StockOpname
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const markStockOpnameReversed = `-- name: MarkStockOpnameReversed :exec
UPDATE stock_opnames
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkStockOpnameReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkStockOpnameReversed(ctx context.Context, arg MarkStockOpnameReversedParams) error {
	_, err := q.db.Exec(ctx, markStockOpnameReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markStockTransferPosted = `-- name: MarkStockTransferPosted :one
UPDATE stock_transfers
SET status = 'posted', doc_number = $1, posted_at = now(), posted_by = $2
WHERE tenant_id = $3 AND id = $4
RETURNING id, tenant_id, doc_number, status, from_warehouse_id, to_warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type MarkStockTransferPostedParams struct {
	DocNumber pgtype.Text
	PostedBy  pgtype.UUID
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkStockTransferPosted(ctx context.Context, arg MarkStockTransferPostedParams) (StockTransfer, error) {
	row := q.db.QueryRow(ctx, markStockTransferPosted,
		arg.DocNumber,
		arg.PostedBy,
		arg.TenantID,
		arg.ID,
	)
	var i StockTransfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const markStockTransferReversed = `-- name: MarkStockTransferReversed :exec
UPDATE stock_transfers
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkStockTransferReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkStockTransferReversed(ctx context.Context, arg MarkStockTransferReversedParams) error {
	_, err := q.db.Exec(ctx, markStockTransferReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const setStockOpnameLineSystemQty = `-- name: SetStockOpnameLineSystemQty :exec
UPDATE stock_opname_lines
SET system_qty = $1
WHERE tenant_id = $2 AND id = $3
`

type SetStockOpnameLineSystemQtyParams struct {
	SystemQty pgtype.Numeric
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SetStockOpnameLineSystemQty(ctx context.Context, arg SetStockOpnameLineSystemQtyParams) error {
	_, err := q.db.Exec(ctx, setStockOpnameLineSystemQty, arg.SystemQty, arg.TenantID, arg.ID)
	return err
}

const sumDeliveredForSOLine = `-- name: SumDeliveredForSOLine :one
SELECT COALESCE(SUM(dl.qty), '0'::numeric) AS delivered_qty
FROM delivery_lines dl
JOIN deliveries d ON d.id = dl.delivery_id
WHERE dl.tenant_id = $1
  AND dl.sales_order_line_id = $2
  AND dl.delivery_id != $3
  AND d.status = 'posted'
  AND d.reverses_id IS NULL
`

type SumDeliveredForSOLineParams struct {
	TenantID          uuid.UUID
	SalesOrderLineID  pgtype.UUID
	ExcludeDeliveryID uuid.UUID
}

// Already-delivered qty for an SO line, excluding the current delivery being posted.
func (q *Queries) SumDeliveredForSOLine(ctx context.Context, arg SumDeliveredForSOLineParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumDeliveredForSOLine, arg.TenantID, arg.SalesOrderLineID, arg.ExcludeDeliveryID)
	var delivered_qty interface{}
	err := row.Scan(&delivered_qty)
	return delivered_qty, err
}

const sumReceivedForPOLine = `-- name: SumReceivedForPOLine :one
SELECT COALESCE(SUM(grl.qty), '0'::numeric) AS received_qty
FROM goods_receipt_lines grl
JOIN goods_receipts gr ON gr.id = grl.goods_receipt_id
WHERE grl.tenant_id = $1
  AND grl.purchase_order_line_id = $2
  AND grl.goods_receipt_id != $3
  AND gr.status = 'posted'
  AND gr.reverses_id IS NULL
`

type SumReceivedForPOLineParams struct {
	TenantID              uuid.UUID
	PurchaseOrderLineID   pgtype.UUID
	ExcludeGoodsReceiptID uuid.UUID
}

// Already-received qty for a PO line, excluding the current goods receipt being posted.
func (q *Queries) SumReceivedForPOLine(ctx context.Context, arg SumReceivedForPOLineParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumReceivedForPOLine, arg.TenantID, arg.PurchaseOrderLineID, arg.ExcludeGoodsReceiptID)
	var received_qty interface{}
	err := row.Scan(&received_qty)
	return received_qty, err
}

const updateDeliveryHeader = `-- name: UpdateDeliveryHeader :one
UPDATE deliveries
SET sales_order_id = $1, customer_id = $2, warehouse_id = $3, doc_date = $4, notes = $5
WHERE tenant_id = $6 AND id = $7
RETURNING id, tenant_id, doc_number, status, sales_order_id, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type UpdateDeliveryHeaderParams struct {
	SalesOrderID pgtype.UUID
	CustomerID   uuid.UUID
	WarehouseID  uuid.UUID
	DocDate      pgtype.Date
	Notes        string
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) UpdateDeliveryHeader(ctx context.Context, arg UpdateDeliveryHeaderParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryHeader,
		arg.SalesOrderID,
		arg.CustomerID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const updateGoodsReceiptHeader = `-- name: UpdateGoodsReceiptHeader :one
UPDATE goods_receipts
SET purchase_order_id = $1, supplier_id = $2, warehouse_id = $3, doc_date = $4, notes = $5
WHERE tenant_id = $6 AND id = $7
RETURNING id, tenant_id, doc_number, status, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type UpdateGoodsReceiptHeaderParams struct {
	PurchaseOrderID pgtype.UUID
	SupplierID      uuid.UUID
	WarehouseID     uuid.UUID
	DocDate         pgtype.Date
	Notes           string
	TenantID        uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateGoodsReceiptHeader(ctx context.Context, arg UpdateGoodsReceiptHeaderParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, updateGoodsReceiptHeader,
		arg.PurchaseOrderID,
		arg.SupplierID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const updatePurchaseOrderHeader = `-- name: UpdatePurchaseOrderHeader :one
UPDATE purchase_orders
SET supplier_id = $1, warehouse_id = $2, doc_date = $3, notes = $4
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, doc_number, status, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type UpdatePurchaseOrderHeaderParams struct {
	SupplierID  uuid.UUID
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdatePurchaseOrderHeader(ctx context.Context, arg UpdatePurchaseOrderHeaderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, updatePurchaseOrderHeader,
		arg.SupplierID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const updateSalesOrderHeader = `-- name: UpdateSalesOrderHeader :one
UPDATE sales_orders
SET customer_id = $1, warehouse_id = $2, doc_date = $3, notes = $4
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, doc_number, status, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type UpdateSalesOrderHeaderParams struct {
	CustomerID  uuid.UUID
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateSalesOrderHeader(ctx context.Context, arg UpdateSalesOrderHeaderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, updateSalesOrderHeader,
		arg.CustomerID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const updateStockAdjustmentHeader = `-- name: UpdateStockAdjustmentHeader :one
UPDATE stock_adjustments
SET warehouse_id = $1, reason = $2, doc_date = $3, notes = $4
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, doc_number, status, warehouse_id, reason, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type UpdateStockAdjustmentHeaderParams struct {
	WarehouseID uuid.UUID
	Reason      string
	DocDate     pgtype.Date
	Notes       string
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateStockAdjustmentHeader(ctx context.Context, arg UpdateStockAdjustmentHeaderParams) (StockAdjustment, error) {
	row := q.db.QueryRow(ctx, updateStockAdjustmentHeader,
		arg.WarehouseID,
		arg.Reason,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i StockAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.Reason,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const updateStockOpnameHeader = `-- name: UpdateStockOpnameHeader :one
UPDATE stock_opnames
SET warehouse_id = $1, doc_date = $2, notes = $3
WHERE tenant_id = $4 AND id = $5
RETURNING id, tenant_id, doc_number, status, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type UpdateStockOpnameHeaderParams struct {
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateStockOpnameHeader(ctx context.Context, arg UpdateStockOpnameHeaderParams) (StockOpname, error) {
	row := q.db.QueryRow(ctx, updateStockOpnameHeader,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i StockOpname
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}

const updateStockTransferHeader = `-- name: UpdateStockTransferHeader :one
UPDATE stock_transfers
SET from_warehouse_id = $1, to_warehouse_id = $2, doc_date = $3, notes = $4
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, doc_number, status, from_warehouse_id, to_warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id, posted_by
`

type UpdateStockTransferHeaderParams struct {
	FromWarehouseID uuid.UUID
	ToWarehouseID   uuid.UUID
	DocDate         pgtype.Date
	Notes           string
	TenantID        uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateStockTransferHeader(ctx context.Context, arg UpdateStockTransferHeaderParams) (StockTransfer, error) {
	row := q.db.QueryRow(ctx, updateStockTransferHeader,
		arg.FromWarehouseID,
		arg.ToWarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i StockTransfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
		&i.PostedBy,
	)
	return i, err
}
