// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDelivery = `-- name: CreateDelivery :one

INSERT INTO deliveries (tenant_id, sales_order_id, customer_id, warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, doc_number, status, sales_order_id, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type CreateDeliveryParams struct {
	TenantID     uuid.UUID
	SalesOrderID pgtype.UUID
	CustomerID   uuid.UUID
	WarehouseID  uuid.UUID
	DocDate      pgtype.Date
	Notes        string
	ReversesID   pgtype.UUID
	Status       string
	CreatedBy    uuid.UUID
}

// ===========================================================================
// Deliveries
// ===========================================================================
func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.TenantID,
		arg.SalesOrderID,
		arg.CustomerID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const createGoodsReceipt = `-- name: CreateGoodsReceipt :one

INSERT INTO goods_receipts (tenant_id, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, doc_number, status, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type CreateGoodsReceiptParams struct {
	TenantID        uuid.UUID
	PurchaseOrderID pgtype.UUID
	SupplierID      uuid.UUID
	WarehouseID     uuid.UUID
	DocDate         pgtype.Date
	Notes           string
	ReversesID      pgtype.UUID
	Status          string
	CreatedBy       uuid.UUID
}

// ===========================================================================
// Goods receipts
// ===========================================================================
func (q *Queries) CreateGoodsReceipt(ctx context.Context, arg CreateGoodsReceiptParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, createGoodsReceipt,
		arg.TenantID,
		arg.PurchaseOrderID,
		arg.SupplierID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one


INSERT INTO purchase_orders (tenant_id, supplier_id, warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, doc_number, status, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type CreatePurchaseOrderParams struct {
	TenantID    uuid.UUID
	SupplierID  uuid.UUID
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	ReversesID  pgtype.UUID
	Status      string
	CreatedBy   uuid.UUID
}

// Document queries (Track C - docs/plans/m1-parallel.md). Draft CRUD for the six
// document types plus the header transitions posting and reversal need. Movement
// writes, gapless numbering, and stock_levels are owned by the Poster (Track B);
// these queries only manage the document tables. Every query is tenant-scoped and
// runs under an app.tenant_id transaction so RLS applies (ADR-0004).
// ===========================================================================
// Purchase orders
// ===========================================================================
func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.TenantID,
		arg.SupplierID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const createSalesOrder = `-- name: CreateSalesOrder :one

INSERT INTO sales_orders (tenant_id, customer_id, warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, doc_number, status, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type CreateSalesOrderParams struct {
	TenantID    uuid.UUID
	CustomerID  uuid.UUID
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	ReversesID  pgtype.UUID
	Status      string
	CreatedBy   uuid.UUID
}

// ===========================================================================
// Sales orders
// ===========================================================================
func (q *Queries) CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, createSalesOrder,
		arg.TenantID,
		arg.CustomerID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const createStockAdjustment = `-- name: CreateStockAdjustment :one

INSERT INTO stock_adjustments (tenant_id, warehouse_id, reason, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, doc_number, status, warehouse_id, reason, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type CreateStockAdjustmentParams struct {
	TenantID    uuid.UUID
	WarehouseID uuid.UUID
	Reason      string
	DocDate     pgtype.Date
	Notes       string
	ReversesID  pgtype.UUID
	Status      string
	CreatedBy   uuid.UUID
}

// ===========================================================================
// Stock adjustments
// ===========================================================================
func (q *Queries) CreateStockAdjustment(ctx context.Context, arg CreateStockAdjustmentParams) (StockAdjustment, error) {
	row := q.db.QueryRow(ctx, createStockAdjustment,
		arg.TenantID,
		arg.WarehouseID,
		arg.Reason,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i StockAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.Reason,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const createStockOpname = `-- name: CreateStockOpname :one

INSERT INTO stock_opnames (tenant_id, warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, doc_number, status, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type CreateStockOpnameParams struct {
	TenantID    uuid.UUID
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	ReversesID  pgtype.UUID
	Status      string
	CreatedBy   uuid.UUID
}

// ===========================================================================
// Stock opnames
// ===========================================================================
func (q *Queries) CreateStockOpname(ctx context.Context, arg CreateStockOpnameParams) (StockOpname, error) {
	row := q.db.QueryRow(ctx, createStockOpname,
		arg.TenantID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i StockOpname
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const createStockTransfer = `-- name: CreateStockTransfer :one

INSERT INTO stock_transfers (tenant_id, from_warehouse_id, to_warehouse_id, doc_date, notes, reverses_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, doc_number, status, from_warehouse_id, to_warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type CreateStockTransferParams struct {
	TenantID        uuid.UUID
	FromWarehouseID uuid.UUID
	ToWarehouseID   uuid.UUID
	DocDate         pgtype.Date
	Notes           string
	ReversesID      pgtype.UUID
	Status          string
	CreatedBy       uuid.UUID
}

// ===========================================================================
// Stock transfers
// ===========================================================================
func (q *Queries) CreateStockTransfer(ctx context.Context, arg CreateStockTransferParams) (StockTransfer, error) {
	row := q.db.QueryRow(ctx, createStockTransfer,
		arg.TenantID,
		arg.FromWarehouseID,
		arg.ToWarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.ReversesID,
		arg.Status,
		arg.CreatedBy,
	)
	var i StockTransfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const deleteDeliveryLines = `-- name: DeleteDeliveryLines :exec
DELETE FROM delivery_lines WHERE tenant_id = $1 AND delivery_id = $2
`

type DeleteDeliveryLinesParams struct {
	TenantID   uuid.UUID
	DeliveryID uuid.UUID
}

func (q *Queries) DeleteDeliveryLines(ctx context.Context, arg DeleteDeliveryLinesParams) error {
	_, err := q.db.Exec(ctx, deleteDeliveryLines, arg.TenantID, arg.DeliveryID)
	return err
}

const deleteGoodsReceiptLines = `-- name: DeleteGoodsReceiptLines :exec
DELETE FROM goods_receipt_lines WHERE tenant_id = $1 AND goods_receipt_id = $2
`

type DeleteGoodsReceiptLinesParams struct {
	TenantID       uuid.UUID
	GoodsReceiptID uuid.UUID
}

func (q *Queries) DeleteGoodsReceiptLines(ctx context.Context, arg DeleteGoodsReceiptLinesParams) error {
	_, err := q.db.Exec(ctx, deleteGoodsReceiptLines, arg.TenantID, arg.GoodsReceiptID)
	return err
}

const deletePurchaseOrderLines = `-- name: DeletePurchaseOrderLines :exec
DELETE FROM purchase_order_lines WHERE tenant_id = $1 AND purchase_order_id = $2
`

type DeletePurchaseOrderLinesParams struct {
	TenantID        uuid.UUID
	PurchaseOrderID uuid.UUID
}

func (q *Queries) DeletePurchaseOrderLines(ctx context.Context, arg DeletePurchaseOrderLinesParams) error {
	_, err := q.db.Exec(ctx, deletePurchaseOrderLines, arg.TenantID, arg.PurchaseOrderID)
	return err
}

const deleteSalesOrderLines = `-- name: DeleteSalesOrderLines :exec
DELETE FROM sales_order_lines WHERE tenant_id = $1 AND sales_order_id = $2
`

type DeleteSalesOrderLinesParams struct {
	TenantID     uuid.UUID
	SalesOrderID uuid.UUID
}

func (q *Queries) DeleteSalesOrderLines(ctx context.Context, arg DeleteSalesOrderLinesParams) error {
	_, err := q.db.Exec(ctx, deleteSalesOrderLines, arg.TenantID, arg.SalesOrderID)
	return err
}

const deleteStockAdjustmentLines = `-- name: DeleteStockAdjustmentLines :exec
DELETE FROM stock_adjustment_lines WHERE tenant_id = $1 AND stock_adjustment_id = $2
`

type DeleteStockAdjustmentLinesParams struct {
	TenantID          uuid.UUID
	StockAdjustmentID uuid.UUID
}

func (q *Queries) DeleteStockAdjustmentLines(ctx context.Context, arg DeleteStockAdjustmentLinesParams) error {
	_, err := q.db.Exec(ctx, deleteStockAdjustmentLines, arg.TenantID, arg.StockAdjustmentID)
	return err
}

const deleteStockOpnameLines = `-- name: DeleteStockOpnameLines :exec
DELETE FROM stock_opname_lines WHERE tenant_id = $1 AND stock_opname_id = $2
`

type DeleteStockOpnameLinesParams struct {
	TenantID      uuid.UUID
	StockOpnameID uuid.UUID
}

func (q *Queries) DeleteStockOpnameLines(ctx context.Context, arg DeleteStockOpnameLinesParams) error {
	_, err := q.db.Exec(ctx, deleteStockOpnameLines, arg.TenantID, arg.StockOpnameID)
	return err
}

const deleteStockTransferLines = `-- name: DeleteStockTransferLines :exec
DELETE FROM stock_transfer_lines WHERE tenant_id = $1 AND stock_transfer_id = $2
`

type DeleteStockTransferLinesParams struct {
	TenantID        uuid.UUID
	StockTransferID uuid.UUID
}

func (q *Queries) DeleteStockTransferLines(ctx context.Context, arg DeleteStockTransferLinesParams) error {
	_, err := q.db.Exec(ctx, deleteStockTransferLines, arg.TenantID, arg.StockTransferID)
	return err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, tenant_id, doc_number, status, sales_order_id, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM deliveries WHERE tenant_id = $1 AND id = $2
`

type GetDeliveryParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetDelivery(ctx context.Context, arg GetDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, arg.TenantID, arg.ID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const getGoodsReceipt = `-- name: GetGoodsReceipt :one
SELECT id, tenant_id, doc_number, status, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM goods_receipts WHERE tenant_id = $1 AND id = $2
`

type GetGoodsReceiptParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetGoodsReceipt(ctx context.Context, arg GetGoodsReceiptParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, getGoodsReceipt, arg.TenantID, arg.ID)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT id, tenant_id, doc_number, status, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM purchase_orders WHERE tenant_id = $1 AND id = $2
`

type GetPurchaseOrderParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrder, arg.TenantID, arg.ID)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const getSalesOrder = `-- name: GetSalesOrder :one
SELECT id, tenant_id, doc_number, status, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM sales_orders WHERE tenant_id = $1 AND id = $2
`

type GetSalesOrderParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetSalesOrder(ctx context.Context, arg GetSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrder, arg.TenantID, arg.ID)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const getStockAdjustment = `-- name: GetStockAdjustment :one
SELECT id, tenant_id, doc_number, status, warehouse_id, reason, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM stock_adjustments WHERE tenant_id = $1 AND id = $2
`

type GetStockAdjustmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetStockAdjustment(ctx context.Context, arg GetStockAdjustmentParams) (StockAdjustment, error) {
	row := q.db.QueryRow(ctx, getStockAdjustment, arg.TenantID, arg.ID)
	var i StockAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.Reason,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const getStockLevelForDoc = `-- name: GetStockLevelForDoc :one

SELECT qty_on_hand, avg_cost
FROM stock_levels
WHERE tenant_id = $1
  AND product_id = $2
  AND warehouse_id = $3
  AND batch_id IS NOT DISTINCT FROM $4
`

type GetStockLevelForDocParams struct {
	TenantID    uuid.UUID
	ProductID   uuid.UUID
	WarehouseID uuid.UUID
	BatchID     pgtype.UUID
}

type GetStockLevelForDocRow struct {
	QtyOnHand pgtype.Numeric
	AvgCost   pgtype.Numeric
}

// ===========================================================================
// Shared: current stock level for opname variance (read the derived cache)
// ===========================================================================
func (q *Queries) GetStockLevelForDoc(ctx context.Context, arg GetStockLevelForDocParams) (GetStockLevelForDocRow, error) {
	row := q.db.QueryRow(ctx, getStockLevelForDoc,
		arg.TenantID,
		arg.ProductID,
		arg.WarehouseID,
		arg.BatchID,
	)
	var i GetStockLevelForDocRow
	err := row.Scan(&i.QtyOnHand, &i.AvgCost)
	return i, err
}

const getStockOpname = `-- name: GetStockOpname :one
SELECT id, tenant_id, doc_number, status, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM stock_opnames WHERE tenant_id = $1 AND id = $2
`

type GetStockOpnameParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetStockOpname(ctx context.Context, arg GetStockOpnameParams) (StockOpname, error) {
	row := q.db.QueryRow(ctx, getStockOpname, arg.TenantID, arg.ID)
	var i StockOpname
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const getStockTransfer = `-- name: GetStockTransfer :one
SELECT id, tenant_id, doc_number, status, from_warehouse_id, to_warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM stock_transfers WHERE tenant_id = $1 AND id = $2
`

type GetStockTransferParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetStockTransfer(ctx context.Context, arg GetStockTransferParams) (StockTransfer, error) {
	row := q.db.QueryRow(ctx, getStockTransfer, arg.TenantID, arg.ID)
	var i StockTransfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const insertDeliveryLine = `-- name: InsertDeliveryLine :one
INSERT INTO delivery_lines (tenant_id, delivery_id, line_no, sales_order_line_id, product_id, batch_id, uom, qty)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, delivery_id, line_no, sales_order_line_id, product_id, batch_id, uom, qty
`

type InsertDeliveryLineParams struct {
	TenantID         uuid.UUID
	DeliveryID       uuid.UUID
	LineNo           int32
	SalesOrderLineID pgtype.UUID
	ProductID        uuid.UUID
	BatchID          pgtype.UUID
	Uom              string
	Qty              pgtype.Numeric
}

func (q *Queries) InsertDeliveryLine(ctx context.Context, arg InsertDeliveryLineParams) (DeliveryLine, error) {
	row := q.db.QueryRow(ctx, insertDeliveryLine,
		arg.TenantID,
		arg.DeliveryID,
		arg.LineNo,
		arg.SalesOrderLineID,
		arg.ProductID,
		arg.BatchID,
		arg.Uom,
		arg.Qty,
	)
	var i DeliveryLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeliveryID,
		&i.LineNo,
		&i.SalesOrderLineID,
		&i.ProductID,
		&i.BatchID,
		&i.Uom,
		&i.Qty,
	)
	return i, err
}

const insertGoodsReceiptLine = `-- name: InsertGoodsReceiptLine :one
INSERT INTO goods_receipt_lines (tenant_id, goods_receipt_id, line_no, purchase_order_line_id, product_id, batch_id, uom, qty, unit_cost)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, goods_receipt_id, line_no, purchase_order_line_id, product_id, batch_id, uom, qty, unit_cost
`

type InsertGoodsReceiptLineParams struct {
	TenantID            uuid.UUID
	GoodsReceiptID      uuid.UUID
	LineNo              int32
	PurchaseOrderLineID pgtype.UUID
	ProductID           uuid.UUID
	BatchID             pgtype.UUID
	Uom                 string
	Qty                 pgtype.Numeric
	UnitCost            pgtype.Numeric
}

func (q *Queries) InsertGoodsReceiptLine(ctx context.Context, arg InsertGoodsReceiptLineParams) (GoodsReceiptLine, error) {
	row := q.db.QueryRow(ctx, insertGoodsReceiptLine,
		arg.TenantID,
		arg.GoodsReceiptID,
		arg.LineNo,
		arg.PurchaseOrderLineID,
		arg.ProductID,
		arg.BatchID,
		arg.Uom,
		arg.Qty,
		arg.UnitCost,
	)
	var i GoodsReceiptLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GoodsReceiptID,
		&i.LineNo,
		&i.PurchaseOrderLineID,
		&i.ProductID,
		&i.BatchID,
		&i.Uom,
		&i.Qty,
		&i.UnitCost,
	)
	return i, err
}

const insertPurchaseOrderLine = `-- name: InsertPurchaseOrderLine :one
INSERT INTO purchase_order_lines (tenant_id, purchase_order_id, line_no, product_id, uom, qty, unit_cost)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, purchase_order_id, line_no, product_id, uom, qty, unit_cost
`

type InsertPurchaseOrderLineParams struct {
	TenantID        uuid.UUID
	PurchaseOrderID uuid.UUID
	LineNo          int32
	ProductID       uuid.UUID
	Uom             string
	Qty             pgtype.Numeric
	UnitCost        pgtype.Numeric
}

func (q *Queries) InsertPurchaseOrderLine(ctx context.Context, arg InsertPurchaseOrderLineParams) (PurchaseOrderLine, error) {
	row := q.db.QueryRow(ctx, insertPurchaseOrderLine,
		arg.TenantID,
		arg.PurchaseOrderID,
		arg.LineNo,
		arg.ProductID,
		arg.Uom,
		arg.Qty,
		arg.UnitCost,
	)
	var i PurchaseOrderLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PurchaseOrderID,
		&i.LineNo,
		&i.ProductID,
		&i.Uom,
		&i.Qty,
		&i.UnitCost,
	)
	return i, err
}

const insertSalesOrderLine = `-- name: InsertSalesOrderLine :one
INSERT INTO sales_order_lines (tenant_id, sales_order_id, line_no, product_id, uom, qty, unit_price)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, sales_order_id, line_no, product_id, uom, qty, unit_price
`

type InsertSalesOrderLineParams struct {
	TenantID     uuid.UUID
	SalesOrderID uuid.UUID
	LineNo       int32
	ProductID    uuid.UUID
	Uom          string
	Qty          pgtype.Numeric
	UnitPrice    pgtype.Numeric
}

func (q *Queries) InsertSalesOrderLine(ctx context.Context, arg InsertSalesOrderLineParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, insertSalesOrderLine,
		arg.TenantID,
		arg.SalesOrderID,
		arg.LineNo,
		arg.ProductID,
		arg.Uom,
		arg.Qty,
		arg.UnitPrice,
	)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.LineNo,
		&i.ProductID,
		&i.Uom,
		&i.Qty,
		&i.UnitPrice,
	)
	return i, err
}

const insertStockAdjustmentLine = `-- name: InsertStockAdjustmentLine :one
INSERT INTO stock_adjustment_lines (tenant_id, stock_adjustment_id, line_no, product_id, batch_id, uom, qty, unit_cost)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, stock_adjustment_id, line_no, product_id, batch_id, uom, qty, unit_cost
`

type InsertStockAdjustmentLineParams struct {
	TenantID          uuid.UUID
	StockAdjustmentID uuid.UUID
	LineNo            int32
	ProductID         uuid.UUID
	BatchID           pgtype.UUID
	Uom               string
	Qty               pgtype.Numeric
	UnitCost          pgtype.Numeric
}

func (q *Queries) InsertStockAdjustmentLine(ctx context.Context, arg InsertStockAdjustmentLineParams) (StockAdjustmentLine, error) {
	row := q.db.QueryRow(ctx, insertStockAdjustmentLine,
		arg.TenantID,
		arg.StockAdjustmentID,
		arg.LineNo,
		arg.ProductID,
		arg.BatchID,
		arg.Uom,
		arg.Qty,
		arg.UnitCost,
	)
	var i StockAdjustmentLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StockAdjustmentID,
		&i.LineNo,
		&i.ProductID,
		&i.BatchID,
		&i.Uom,
		&i.Qty,
		&i.UnitCost,
	)
	return i, err
}

const insertStockOpnameLine = `-- name: InsertStockOpnameLine :one
INSERT INTO stock_opname_lines (tenant_id, stock_opname_id, line_no, product_id, batch_id, uom, counted_qty)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, stock_opname_id, line_no, product_id, batch_id, uom, counted_qty
`

type InsertStockOpnameLineParams struct {
	TenantID      uuid.UUID
	StockOpnameID uuid.UUID
	LineNo        int32
	ProductID     uuid.UUID
	BatchID       pgtype.UUID
	Uom           string
	CountedQty    pgtype.Numeric
}

func (q *Queries) InsertStockOpnameLine(ctx context.Context, arg InsertStockOpnameLineParams) (StockOpnameLine, error) {
	row := q.db.QueryRow(ctx, insertStockOpnameLine,
		arg.TenantID,
		arg.StockOpnameID,
		arg.LineNo,
		arg.ProductID,
		arg.BatchID,
		arg.Uom,
		arg.CountedQty,
	)
	var i StockOpnameLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StockOpnameID,
		&i.LineNo,
		&i.ProductID,
		&i.BatchID,
		&i.Uom,
		&i.CountedQty,
	)
	return i, err
}

const insertStockTransferLine = `-- name: InsertStockTransferLine :one
INSERT INTO stock_transfer_lines (tenant_id, stock_transfer_id, line_no, product_id, batch_id, uom, qty)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, stock_transfer_id, line_no, product_id, batch_id, uom, qty
`

type InsertStockTransferLineParams struct {
	TenantID        uuid.UUID
	StockTransferID uuid.UUID
	LineNo          int32
	ProductID       uuid.UUID
	BatchID         pgtype.UUID
	Uom             string
	Qty             pgtype.Numeric
}

func (q *Queries) InsertStockTransferLine(ctx context.Context, arg InsertStockTransferLineParams) (StockTransferLine, error) {
	row := q.db.QueryRow(ctx, insertStockTransferLine,
		arg.TenantID,
		arg.StockTransferID,
		arg.LineNo,
		arg.ProductID,
		arg.BatchID,
		arg.Uom,
		arg.Qty,
	)
	var i StockTransferLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StockTransferID,
		&i.LineNo,
		&i.ProductID,
		&i.BatchID,
		&i.Uom,
		&i.Qty,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, tenant_id, doc_number, status, sales_order_id, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM deliveries WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeliveries(ctx context.Context, tenantID uuid.UUID) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.SalesOrderID,
			&i.CustomerID,
			&i.WarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryLines = `-- name: ListDeliveryLines :many
SELECT id, tenant_id, delivery_id, line_no, sales_order_line_id, product_id, batch_id, uom, qty FROM delivery_lines WHERE tenant_id = $1 AND delivery_id = $2 ORDER BY line_no
`

type ListDeliveryLinesParams struct {
	TenantID   uuid.UUID
	DeliveryID uuid.UUID
}

func (q *Queries) ListDeliveryLines(ctx context.Context, arg ListDeliveryLinesParams) ([]DeliveryLine, error) {
	rows, err := q.db.Query(ctx, listDeliveryLines, arg.TenantID, arg.DeliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryLine
	for rows.Next() {
		var i DeliveryLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DeliveryID,
			&i.LineNo,
			&i.SalesOrderLineID,
			&i.ProductID,
			&i.BatchID,
			&i.Uom,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoodsReceiptLines = `-- name: ListGoodsReceiptLines :many
SELECT id, tenant_id, goods_receipt_id, line_no, purchase_order_line_id, product_id, batch_id, uom, qty, unit_cost FROM goods_receipt_lines WHERE tenant_id = $1 AND goods_receipt_id = $2 ORDER BY line_no
`

type ListGoodsReceiptLinesParams struct {
	TenantID       uuid.UUID
	GoodsReceiptID uuid.UUID
}

func (q *Queries) ListGoodsReceiptLines(ctx context.Context, arg ListGoodsReceiptLinesParams) ([]GoodsReceiptLine, error) {
	rows, err := q.db.Query(ctx, listGoodsReceiptLines, arg.TenantID, arg.GoodsReceiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsReceiptLine
	for rows.Next() {
		var i GoodsReceiptLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.GoodsReceiptID,
			&i.LineNo,
			&i.PurchaseOrderLineID,
			&i.ProductID,
			&i.BatchID,
			&i.Uom,
			&i.Qty,
			&i.UnitCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoodsReceipts = `-- name: ListGoodsReceipts :many
SELECT id, tenant_id, doc_number, status, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM goods_receipts WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGoodsReceipts(ctx context.Context, tenantID uuid.UUID) ([]GoodsReceipt, error) {
	rows, err := q.db.Query(ctx, listGoodsReceipts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsReceipt
	for rows.Next() {
		var i GoodsReceipt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.PurchaseOrderID,
			&i.SupplierID,
			&i.WarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrderLines = `-- name: ListPurchaseOrderLines :many
SELECT id, tenant_id, purchase_order_id, line_no, product_id, uom, qty, unit_cost FROM purchase_order_lines WHERE tenant_id = $1 AND purchase_order_id = $2 ORDER BY line_no
`

type ListPurchaseOrderLinesParams struct {
	TenantID        uuid.UUID
	PurchaseOrderID uuid.UUID
}

func (q *Queries) ListPurchaseOrderLines(ctx context.Context, arg ListPurchaseOrderLinesParams) ([]PurchaseOrderLine, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderLines, arg.TenantID, arg.PurchaseOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrderLine
	for rows.Next() {
		var i PurchaseOrderLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PurchaseOrderID,
			&i.LineNo,
			&i.ProductID,
			&i.Uom,
			&i.Qty,
			&i.UnitCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT id, tenant_id, doc_number, status, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM purchase_orders WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPurchaseOrders(ctx context.Context, tenantID uuid.UUID) ([]PurchaseOrder, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrder
	for rows.Next() {
		var i PurchaseOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.SupplierID,
			&i.WarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrderLines = `-- name: ListSalesOrderLines :many
SELECT id, tenant_id, sales_order_id, line_no, product_id, uom, qty, unit_price FROM sales_order_lines WHERE tenant_id = $1 AND sales_order_id = $2 ORDER BY line_no
`

type ListSalesOrderLinesParams struct {
	TenantID     uuid.UUID
	SalesOrderID uuid.UUID
}

func (q *Queries) ListSalesOrderLines(ctx context.Context, arg ListSalesOrderLinesParams) ([]SalesOrderLine, error) {
	rows, err := q.db.Query(ctx, listSalesOrderLines, arg.TenantID, arg.SalesOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesOrderLine
	for rows.Next() {
		var i SalesOrderLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SalesOrderID,
			&i.LineNo,
			&i.ProductID,
			&i.Uom,
			&i.Qty,
			&i.UnitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrders = `-- name: ListSalesOrders :many
SELECT id, tenant_id, doc_number, status, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM sales_orders WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSalesOrders(ctx context.Context, tenantID uuid.UUID) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, listSalesOrders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesOrder
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.CustomerID,
			&i.WarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockAdjustmentLines = `-- name: ListStockAdjustmentLines :many
SELECT id, tenant_id, stock_adjustment_id, line_no, product_id, batch_id, uom, qty, unit_cost FROM stock_adjustment_lines WHERE tenant_id = $1 AND stock_adjustment_id = $2 ORDER BY line_no
`

type ListStockAdjustmentLinesParams struct {
	TenantID          uuid.UUID
	StockAdjustmentID uuid.UUID
}

func (q *Queries) ListStockAdjustmentLines(ctx context.Context, arg ListStockAdjustmentLinesParams) ([]StockAdjustmentLine, error) {
	rows, err := q.db.Query(ctx, listStockAdjustmentLines, arg.TenantID, arg.StockAdjustmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockAdjustmentLine
	for rows.Next() {
		var i StockAdjustmentLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StockAdjustmentID,
			&i.LineNo,
			&i.ProductID,
			&i.BatchID,
			&i.Uom,
			&i.Qty,
			&i.UnitCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockAdjustments = `-- name: ListStockAdjustments :many
SELECT id, tenant_id, doc_number, status, warehouse_id, reason, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM stock_adjustments WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStockAdjustments(ctx context.Context, tenantID uuid.UUID) ([]StockAdjustment, error) {
	rows, err := q.db.Query(ctx, listStockAdjustments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockAdjustment
	for rows.Next() {
		var i StockAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.WarehouseID,
			&i.Reason,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockOpnameLines = `-- name: ListStockOpnameLines :many
SELECT id, tenant_id, stock_opname_id, line_no, product_id, batch_id, uom, counted_qty FROM stock_opname_lines WHERE tenant_id = $1 AND stock_opname_id = $2 ORDER BY line_no
`

type ListStockOpnameLinesParams struct {
	TenantID      uuid.UUID
	StockOpnameID uuid.UUID
}

func (q *Queries) ListStockOpnameLines(ctx context.Context, arg ListStockOpnameLinesParams) ([]StockOpnameLine, error) {
	rows, err := q.db.Query(ctx, listStockOpnameLines, arg.TenantID, arg.StockOpnameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockOpnameLine
	for rows.Next() {
		var i StockOpnameLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StockOpnameID,
			&i.LineNo,
			&i.ProductID,
			&i.BatchID,
			&i.Uom,
			&i.CountedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockOpnames = `-- name: ListStockOpnames :many
SELECT id, tenant_id, doc_number, status, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM stock_opnames WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStockOpnames(ctx context.Context, tenantID uuid.UUID) ([]StockOpname, error) {
	rows, err := q.db.Query(ctx, listStockOpnames, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockOpname
	for rows.Next() {
		var i StockOpname
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.WarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockTransferLines = `-- name: ListStockTransferLines :many
SELECT id, tenant_id, stock_transfer_id, line_no, product_id, batch_id, uom, qty FROM stock_transfer_lines WHERE tenant_id = $1 AND stock_transfer_id = $2 ORDER BY line_no
`

type ListStockTransferLinesParams struct {
	TenantID        uuid.UUID
	StockTransferID uuid.UUID
}

func (q *Queries) ListStockTransferLines(ctx context.Context, arg ListStockTransferLinesParams) ([]StockTransferLine, error) {
	rows, err := q.db.Query(ctx, listStockTransferLines, arg.TenantID, arg.StockTransferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockTransferLine
	for rows.Next() {
		var i StockTransferLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StockTransferID,
			&i.LineNo,
			&i.ProductID,
			&i.BatchID,
			&i.Uom,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockTransfers = `-- name: ListStockTransfers :many
SELECT id, tenant_id, doc_number, status, from_warehouse_id, to_warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id FROM stock_transfers WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStockTransfers(ctx context.Context, tenantID uuid.UUID) ([]StockTransfer, error) {
	rows, err := q.db.Query(ctx, listStockTransfers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockTransfer
	for rows.Next() {
		var i StockTransfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocNumber,
			&i.Status,
			&i.FromWarehouseID,
			&i.ToWarehouseID,
			&i.DocDate,
			&i.Notes,
			&i.PostedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReversesID,
			&i.ReversedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryPosted = `-- name: MarkDeliveryPosted :one
UPDATE deliveries
SET status = 'posted', doc_number = $1, posted_at = now()
WHERE tenant_id = $2 AND id = $3
RETURNING id, tenant_id, doc_number, status, sales_order_id, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type MarkDeliveryPostedParams struct {
	DocNumber pgtype.Text
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkDeliveryPosted(ctx context.Context, arg MarkDeliveryPostedParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, markDeliveryPosted, arg.DocNumber, arg.TenantID, arg.ID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const markDeliveryReversed = `-- name: MarkDeliveryReversed :exec
UPDATE deliveries
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkDeliveryReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkDeliveryReversed(ctx context.Context, arg MarkDeliveryReversedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markGoodsReceiptPosted = `-- name: MarkGoodsReceiptPosted :one
UPDATE goods_receipts
SET status = 'posted', doc_number = $1, posted_at = now()
WHERE tenant_id = $2 AND id = $3
RETURNING id, tenant_id, doc_number, status, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type MarkGoodsReceiptPostedParams struct {
	DocNumber pgtype.Text
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkGoodsReceiptPosted(ctx context.Context, arg MarkGoodsReceiptPostedParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, markGoodsReceiptPosted, arg.DocNumber, arg.TenantID, arg.ID)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const markGoodsReceiptReversed = `-- name: MarkGoodsReceiptReversed :exec
UPDATE goods_receipts
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkGoodsReceiptReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkGoodsReceiptReversed(ctx context.Context, arg MarkGoodsReceiptReversedParams) error {
	_, err := q.db.Exec(ctx, markGoodsReceiptReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markPurchaseOrderPosted = `-- name: MarkPurchaseOrderPosted :one
UPDATE purchase_orders
SET status = 'posted', doc_number = $1, posted_at = now()
WHERE tenant_id = $2 AND id = $3
RETURNING id, tenant_id, doc_number, status, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type MarkPurchaseOrderPostedParams struct {
	DocNumber pgtype.Text
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkPurchaseOrderPosted(ctx context.Context, arg MarkPurchaseOrderPostedParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, markPurchaseOrderPosted, arg.DocNumber, arg.TenantID, arg.ID)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const markPurchaseOrderReversed = `-- name: MarkPurchaseOrderReversed :exec
UPDATE purchase_orders
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkPurchaseOrderReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkPurchaseOrderReversed(ctx context.Context, arg MarkPurchaseOrderReversedParams) error {
	_, err := q.db.Exec(ctx, markPurchaseOrderReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markSalesOrderPosted = `-- name: MarkSalesOrderPosted :one
UPDATE sales_orders
SET status = 'posted', doc_number = $1, posted_at = now()
WHERE tenant_id = $2 AND id = $3
RETURNING id, tenant_id, doc_number, status, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type MarkSalesOrderPostedParams struct {
	DocNumber pgtype.Text
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkSalesOrderPosted(ctx context.Context, arg MarkSalesOrderPostedParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, markSalesOrderPosted, arg.DocNumber, arg.TenantID, arg.ID)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const markSalesOrderReversed = `-- name: MarkSalesOrderReversed :exec
UPDATE sales_orders
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkSalesOrderReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkSalesOrderReversed(ctx context.Context, arg MarkSalesOrderReversedParams) error {
	_, err := q.db.Exec(ctx, markSalesOrderReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markStockAdjustmentPosted = `-- name: MarkStockAdjustmentPosted :one
UPDATE stock_adjustments
SET status = 'posted', doc_number = $1, posted_at = now()
WHERE tenant_id = $2 AND id = $3
RETURNING id, tenant_id, doc_number, status, warehouse_id, reason, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type MarkStockAdjustmentPostedParams struct {
	DocNumber pgtype.Text
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkStockAdjustmentPosted(ctx context.Context, arg MarkStockAdjustmentPostedParams) (StockAdjustment, error) {
	row := q.db.QueryRow(ctx, markStockAdjustmentPosted, arg.DocNumber, arg.TenantID, arg.ID)
	var i StockAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.Reason,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const markStockAdjustmentReversed = `-- name: MarkStockAdjustmentReversed :exec
UPDATE stock_adjustments
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkStockAdjustmentReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkStockAdjustmentReversed(ctx context.Context, arg MarkStockAdjustmentReversedParams) error {
	_, err := q.db.Exec(ctx, markStockAdjustmentReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markStockOpnamePosted = `-- name: MarkStockOpnamePosted :one
UPDATE stock_opnames
SET status = 'posted', doc_number = $1, posted_at = now()
WHERE tenant_id = $2 AND id = $3
RETURNING id, tenant_id, doc_number, status, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type MarkStockOpnamePostedParams struct {
	DocNumber pgtype.Text
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkStockOpnamePosted(ctx context.Context, arg MarkStockOpnamePostedParams) (StockOpname, error) {
	row := q.db.QueryRow(ctx, markStockOpnamePosted, arg.DocNumber, arg.TenantID, arg.ID)
	var i StockOpname
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const markStockOpnameReversed = `-- name: MarkStockOpnameReversed :exec
UPDATE stock_opnames
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkStockOpnameReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkStockOpnameReversed(ctx context.Context, arg MarkStockOpnameReversedParams) error {
	_, err := q.db.Exec(ctx, markStockOpnameReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const markStockTransferPosted = `-- name: MarkStockTransferPosted :one
UPDATE stock_transfers
SET status = 'posted', doc_number = $1, posted_at = now()
WHERE tenant_id = $2 AND id = $3
RETURNING id, tenant_id, doc_number, status, from_warehouse_id, to_warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type MarkStockTransferPostedParams struct {
	DocNumber pgtype.Text
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkStockTransferPosted(ctx context.Context, arg MarkStockTransferPostedParams) (StockTransfer, error) {
	row := q.db.QueryRow(ctx, markStockTransferPosted, arg.DocNumber, arg.TenantID, arg.ID)
	var i StockTransfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const markStockTransferReversed = `-- name: MarkStockTransferReversed :exec
UPDATE stock_transfers
SET status = 'reversed', reversed_by_id = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkStockTransferReversedParams struct {
	ReversedByID pgtype.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) MarkStockTransferReversed(ctx context.Context, arg MarkStockTransferReversedParams) error {
	_, err := q.db.Exec(ctx, markStockTransferReversed, arg.ReversedByID, arg.TenantID, arg.ID)
	return err
}

const updateDeliveryHeader = `-- name: UpdateDeliveryHeader :one
UPDATE deliveries
SET sales_order_id = $1, customer_id = $2, warehouse_id = $3, doc_date = $4, notes = $5
WHERE tenant_id = $6 AND id = $7
RETURNING id, tenant_id, doc_number, status, sales_order_id, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type UpdateDeliveryHeaderParams struct {
	SalesOrderID pgtype.UUID
	CustomerID   uuid.UUID
	WarehouseID  uuid.UUID
	DocDate      pgtype.Date
	Notes        string
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) UpdateDeliveryHeader(ctx context.Context, arg UpdateDeliveryHeaderParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryHeader,
		arg.SalesOrderID,
		arg.CustomerID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const updateGoodsReceiptHeader = `-- name: UpdateGoodsReceiptHeader :one
UPDATE goods_receipts
SET purchase_order_id = $1, supplier_id = $2, warehouse_id = $3, doc_date = $4, notes = $5
WHERE tenant_id = $6 AND id = $7
RETURNING id, tenant_id, doc_number, status, purchase_order_id, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type UpdateGoodsReceiptHeaderParams struct {
	PurchaseOrderID pgtype.UUID
	SupplierID      uuid.UUID
	WarehouseID     uuid.UUID
	DocDate         pgtype.Date
	Notes           string
	TenantID        uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateGoodsReceiptHeader(ctx context.Context, arg UpdateGoodsReceiptHeaderParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, updateGoodsReceiptHeader,
		arg.PurchaseOrderID,
		arg.SupplierID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const updatePurchaseOrderHeader = `-- name: UpdatePurchaseOrderHeader :one
UPDATE purchase_orders
SET supplier_id = $1, warehouse_id = $2, doc_date = $3, notes = $4
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, doc_number, status, supplier_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type UpdatePurchaseOrderHeaderParams struct {
	SupplierID  uuid.UUID
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdatePurchaseOrderHeader(ctx context.Context, arg UpdatePurchaseOrderHeaderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, updatePurchaseOrderHeader,
		arg.SupplierID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.SupplierID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const updateSalesOrderHeader = `-- name: UpdateSalesOrderHeader :one
UPDATE sales_orders
SET customer_id = $1, warehouse_id = $2, doc_date = $3, notes = $4
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, doc_number, status, customer_id, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type UpdateSalesOrderHeaderParams struct {
	CustomerID  uuid.UUID
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateSalesOrderHeader(ctx context.Context, arg UpdateSalesOrderHeaderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, updateSalesOrderHeader,
		arg.CustomerID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.CustomerID,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const updateStockAdjustmentHeader = `-- name: UpdateStockAdjustmentHeader :one
UPDATE stock_adjustments
SET warehouse_id = $1, reason = $2, doc_date = $3, notes = $4
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, doc_number, status, warehouse_id, reason, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type UpdateStockAdjustmentHeaderParams struct {
	WarehouseID uuid.UUID
	Reason      string
	DocDate     pgtype.Date
	Notes       string
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateStockAdjustmentHeader(ctx context.Context, arg UpdateStockAdjustmentHeaderParams) (StockAdjustment, error) {
	row := q.db.QueryRow(ctx, updateStockAdjustmentHeader,
		arg.WarehouseID,
		arg.Reason,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i StockAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.Reason,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const updateStockOpnameHeader = `-- name: UpdateStockOpnameHeader :one
UPDATE stock_opnames
SET warehouse_id = $1, doc_date = $2, notes = $3
WHERE tenant_id = $4 AND id = $5
RETURNING id, tenant_id, doc_number, status, warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type UpdateStockOpnameHeaderParams struct {
	WarehouseID uuid.UUID
	DocDate     pgtype.Date
	Notes       string
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateStockOpnameHeader(ctx context.Context, arg UpdateStockOpnameHeaderParams) (StockOpname, error) {
	row := q.db.QueryRow(ctx, updateStockOpnameHeader,
		arg.WarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i StockOpname
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.WarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}

const updateStockTransferHeader = `-- name: UpdateStockTransferHeader :one
UPDATE stock_transfers
SET from_warehouse_id = $1, to_warehouse_id = $2, doc_date = $3, notes = $4
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, doc_number, status, from_warehouse_id, to_warehouse_id, doc_date, notes, posted_at, created_at, created_by, reverses_id, reversed_by_id
`

type UpdateStockTransferHeaderParams struct {
	FromWarehouseID uuid.UUID
	ToWarehouseID   uuid.UUID
	DocDate         pgtype.Date
	Notes           string
	TenantID        uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateStockTransferHeader(ctx context.Context, arg UpdateStockTransferHeaderParams) (StockTransfer, error) {
	row := q.db.QueryRow(ctx, updateStockTransferHeader,
		arg.FromWarehouseID,
		arg.ToWarehouseID,
		arg.DocDate,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	var i StockTransfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocNumber,
		&i.Status,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.DocDate,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReversesID,
		&i.ReversedByID,
	)
	return i, err
}
