// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (tenant_id, role, token, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, role, token, created_by, expires_at, created_at
`

type CreateInvitationParams struct {
	TenantID  uuid.UUID
	Role      string
	Token     string
	CreatedBy uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.TenantID,
		arg.Role,
		arg.Token,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.Token,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :execrows
DELETE FROM invitations
WHERE tenant_id = $1 AND id = $2
`

type DeleteInvitationParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvitation, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT i.id, i.tenant_id, i.role, i.token, i.created_by, i.expires_at, i.created_at, t.name AS tenant_name
FROM invitations i
JOIN tenants t ON t.id = i.tenant_id
WHERE i.token = $1
`

type GetInvitationByTokenRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Role       string
	Token      string
	CreatedBy  uuid.UUID
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	TenantName string
}

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (GetInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i GetInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.Token,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.TenantName,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, tenant_id, role, token, created_by, expires_at, created_at FROM invitations
WHERE tenant_id = $1 AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListInvitations(ctx context.Context, tenantID uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Role,
			&i.Token,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
