// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM memberships
WHERE tenant_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM memberships
WHERE tenant_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, arg.TenantID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id, u.name, u.email, m.role
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.tenant_id = $1
ORDER BY u.name
`

type ListMembersRow struct {
	UserID uuid.UUID
	Name   string
	Email  string
	Role   string
}

func (q *Queries) ListMembers(ctx context.Context, tenantID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE memberships
SET role = $3
WHERE tenant_id = $1 AND user_id = $2
RETURNING id, user_id, tenant_id, role, created_at
`

type UpdateMembershipRoleParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	Role     string
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.TenantID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
