// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, tenant_id, role, created_at FROM memberships
WHERE user_id = $1 AND tenant_id = $2
`

type GetMembershipParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.TenantID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT m.role, t.id AS tenant_id, t.name AS tenant_name, t.active AS tenant_active
FROM memberships m
JOIN tenants t ON t.id = m.tenant_id
WHERE m.user_id = $1
ORDER BY t.name
`

type ListMembershipsForUserRow struct {
	Role         string
	TenantID     uuid.UUID
	TenantName   string
	TenantActive bool
}

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsForUserRow
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.Role,
			&i.TenantID,
			&i.TenantName,
			&i.TenantActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
