// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Invitation struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Role      string
	Token     string
	CreatedBy uuid.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Membership struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TenantID  uuid.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ActiveTenantID pgtype.UUID
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type Tenant struct {
	ID                   uuid.UUID
	Name                 string
	LegalName            string
	CostingMethod        string
	FiscalYearStartMonth int32
	Active               bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Warehouse struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Code      string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
