// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partners.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPartner = `-- name: CreatePartner :one
INSERT INTO partners (tenant_id, code, name, is_supplier, is_customer)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, code, name, is_supplier, is_customer, status, created_at, updated_at
`

type CreatePartnerParams struct {
	TenantID   uuid.UUID
	Code       pgtype.Text
	Name       string
	IsSupplier bool
	IsCustomer bool
}

func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) (Partner, error) {
	row := q.db.QueryRow(ctx, createPartner,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.IsSupplier,
		arg.IsCustomer,
	)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.IsSupplier,
		&i.IsCustomer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartner = `-- name: GetPartner :one
SELECT id, tenant_id, code, name, is_supplier, is_customer, status, created_at, updated_at FROM partners
WHERE tenant_id = $1 AND id = $2
`

type GetPartnerParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetPartner(ctx context.Context, arg GetPartnerParams) (Partner, error) {
	row := q.db.QueryRow(ctx, getPartner, arg.TenantID, arg.ID)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.IsSupplier,
		&i.IsCustomer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPartners = `-- name: ListPartners :many
SELECT id, tenant_id, code, name, is_supplier, is_customer, status, created_at, updated_at FROM partners
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND (NOT $3::boolean OR is_supplier)
  AND (NOT $4::boolean OR is_customer)
  AND ($5::text IS NULL
       OR name ILIKE '%' || $5 || '%'
       OR code ILIKE '%' || $5 || '%')
ORDER BY
  CASE WHEN $5::text IS NOT NULL
       THEN -GREATEST(similarity(name, $5::text), similarity(code, $5::text))
  END NULLS LAST,
  name
`

type ListPartnersParams struct {
	TenantID     uuid.UUID
	Status       pgtype.Text
	OnlySupplier bool
	OnlyCustomer bool
	Q            pgtype.Text
}

func (q *Queries) ListPartners(ctx context.Context, arg ListPartnersParams) ([]Partner, error) {
	rows, err := q.db.Query(ctx, listPartners,
		arg.TenantID,
		arg.Status,
		arg.OnlySupplier,
		arg.OnlyCustomer,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partner
	for rows.Next() {
		var i Partner
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.IsSupplier,
			&i.IsCustomer,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartner = `-- name: UpdatePartner :one
UPDATE partners
SET code = $3,
    name = $4,
    is_supplier = $5,
    is_customer = $6,
    status = $7,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, code, name, is_supplier, is_customer, status, created_at, updated_at
`

type UpdatePartnerParams struct {
	TenantID   uuid.UUID
	ID         uuid.UUID
	Code       pgtype.Text
	Name       string
	IsSupplier bool
	IsCustomer bool
	Status     string
}

func (q *Queries) UpdatePartner(ctx context.Context, arg UpdatePartnerParams) (Partner, error) {
	row := q.db.QueryRow(ctx, updatePartner,
		arg.TenantID,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.IsSupplier,
		arg.IsCustomer,
		arg.Status,
	)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.IsSupplier,
		&i.IsCustomer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
