// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posting.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getStockLevel = `-- name: GetStockLevel :one
SELECT qty_on_hand, avg_cost
FROM stock_levels
WHERE tenant_id = $1
  AND product_id = $2
  AND warehouse_id = $3
  AND batch_id IS NOT DISTINCT FROM $4
`

type GetStockLevelParams struct {
	TenantID    uuid.UUID
	ProductID   uuid.UUID
	WarehouseID uuid.UUID
	BatchID     pgtype.UUID
}

type GetStockLevelRow struct {
	QtyOnHand pgtype.Numeric
	AvgCost   pgtype.Numeric
}

// GetStockLevel returns the cached level for a key, if any.
func (q *Queries) GetStockLevel(ctx context.Context, arg GetStockLevelParams) (GetStockLevelRow, error) {
	row := q.db.QueryRow(ctx, getStockLevel,
		arg.TenantID,
		arg.ProductID,
		arg.WarehouseID,
		arg.BatchID,
	)
	var i GetStockLevelRow
	err := row.Scan(&i.QtyOnHand, &i.AvgCost)
	return i, err
}

const insertMovement = `-- name: InsertMovement :one
INSERT INTO stock_movements (
    id, tenant_id, product_id, warehouse_id, batch_id,
    qty_base, unit_cost, movement_type, doc_type, doc_id, doc_line_id,
    effective_at, seq, is_provisional, created_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15
)
RETURNING id
`

type InsertMovementParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	ProductID     uuid.UUID
	WarehouseID   uuid.UUID
	BatchID       pgtype.UUID
	QtyBase       pgtype.Numeric
	UnitCost      pgtype.Numeric
	MovementType  string
	DocType       string
	DocID         uuid.UUID
	DocLineID     pgtype.UUID
	EffectiveAt   pgtype.Timestamptz
	Seq           int64
	IsProvisional bool
	CreatedBy     uuid.UUID
}

// InsertMovement appends one journal row. stock_movements is append-only
// (ADR-0001); there is no update/delete counterpart.
func (q *Queries) InsertMovement(ctx context.Context, arg InsertMovementParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMovement,
		arg.ID,
		arg.TenantID,
		arg.ProductID,
		arg.WarehouseID,
		arg.BatchID,
		arg.QtyBase,
		arg.UnitCost,
		arg.MovementType,
		arg.DocType,
		arg.DocID,
		arg.DocLineID,
		arg.EffectiveAt,
		arg.Seq,
		arg.IsProvisional,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const keyMovements = `-- name: KeyMovements :many
SELECT id, qty_base, unit_cost, movement_type, effective_at, seq, is_provisional
FROM stock_movements
WHERE tenant_id = $1
  AND product_id = $2
  AND warehouse_id = $3
  AND batch_id IS NOT DISTINCT FROM $4
ORDER BY effective_at, seq
`

type KeyMovementsParams struct {
	TenantID    uuid.UUID
	ProductID   uuid.UUID
	WarehouseID uuid.UUID
	BatchID     pgtype.UUID
}

type KeyMovementsRow struct {
	ID            uuid.UUID
	QtyBase       pgtype.Numeric
	UnitCost      pgtype.Numeric
	MovementType  string
	EffectiveAt   pgtype.Timestamptz
	Seq           int64
	IsProvisional bool
}

// KeyMovements returns every movement for a key in journal order
// (effective_at, seq). The poster re-folds the whole ordered slice through the
// costing engine so stock_levels is always a faithful reduction of the
// append-only journal (ADR-0001), never drifting from it.
func (q *Queries) KeyMovements(ctx context.Context, arg KeyMovementsParams) ([]KeyMovementsRow, error) {
	rows, err := q.db.Query(ctx, keyMovements,
		arg.TenantID,
		arg.ProductID,
		arg.WarehouseID,
		arg.BatchID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeyMovementsRow
	for rows.Next() {
		var i KeyMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.QtyBase,
			&i.UnitCost,
			&i.MovementType,
			&i.EffectiveAt,
			&i.Seq,
			&i.IsProvisional,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvisionalMovements = `-- name: ListProvisionalMovements :many
SELECT id, product_id, warehouse_id, batch_id, qty_base, unit_cost,
       movement_type, doc_type, doc_id, effective_at, seq, created_at
FROM stock_movements
WHERE tenant_id = $1
  AND is_provisional
  AND reconciled_by_movement_id IS NULL
ORDER BY effective_at DESC, seq DESC
`

type ListProvisionalMovementsRow struct {
	ID           uuid.UUID
	ProductID    uuid.UUID
	WarehouseID  uuid.UUID
	BatchID      pgtype.UUID
	QtyBase      pgtype.Numeric
	UnitCost     pgtype.Numeric
	MovementType string
	DocType      string
	DocID        uuid.UUID
	EffectiveAt  pgtype.Timestamptz
	Seq          int64
	CreatedAt    pgtype.Timestamptz
}

// ListProvisionalMovements is the reconciliation worklist (ADR-0003): every
// provisional movement for a tenant not yet reconciled, newest first.
func (q *Queries) ListProvisionalMovements(ctx context.Context, tenantID uuid.UUID) ([]ListProvisionalMovementsRow, error) {
	rows, err := q.db.Query(ctx, listProvisionalMovements, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProvisionalMovementsRow
	for rows.Next() {
		var i ListProvisionalMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.WarehouseID,
			&i.BatchID,
			&i.QtyBase,
			&i.UnitCost,
			&i.MovementType,
			&i.DocType,
			&i.DocID,
			&i.EffectiveAt,
			&i.Seq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStockKey = `-- name: LockStockKey :exec

SELECT pg_advisory_xact_lock(
    hashtextextended($1::text || '|' || $2::text || '|' || $3::text, 0)
)
`

type LockStockKeyParams struct {
	TenantID    string
	ProductID   string
	WarehouseID string
}

// Posting-path queries (Track B). Each posting runs in one transaction that
// takes a per-key advisory lock, appends append-only stock_movements rows,
// upserts the derived stock_levels cache, and assigns a gapless document number.
// LockStockKey takes a transaction-scoped advisory lock for one
// (tenant, product, warehouse) key. Concurrent postings that touch the same key
// serialize here, so per-key seq and stock_levels stay consistent (PLAN.md
// section 3). The lock is released automatically at transaction end.
func (q *Queries) LockStockKey(ctx context.Context, arg LockStockKeyParams) error {
	_, err := q.db.Exec(ctx, lockStockKey, arg.TenantID, arg.ProductID, arg.WarehouseID)
	return err
}

const maxMovementSeq = `-- name: MaxMovementSeq :one
SELECT COALESCE(MAX(seq), 0)::bigint AS max_seq
FROM stock_movements
WHERE tenant_id = $1
  AND product_id = $2
  AND warehouse_id = $3
  AND batch_id IS NOT DISTINCT FROM $4
`

type MaxMovementSeqParams struct {
	TenantID    uuid.UUID
	ProductID   uuid.UUID
	WarehouseID uuid.UUID
	BatchID     pgtype.UUID
}

// MaxMovementSeq returns the current highest seq for a key, or 0 when the key
// has no movements yet. The next movement's seq is this + 1. Batch is matched
// with IS NOT DISTINCT FROM so the no-batch row (NULL) compares equal.
func (q *Queries) MaxMovementSeq(ctx context.Context, arg MaxMovementSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, maxMovementSeq,
		arg.TenantID,
		arg.ProductID,
		arg.WarehouseID,
		arg.BatchID,
	)
	var max_seq int64
	err := row.Scan(&max_seq)
	return max_seq, err
}

const nextDocumentNumber = `-- name: NextDocumentNumber :one
INSERT INTO document_number_sequences (tenant_id, doc_type, year, next_seq)
VALUES ($1, $2, $3, 2)
ON CONFLICT (tenant_id, doc_type, year) DO UPDATE
SET next_seq = document_number_sequences.next_seq + 1
RETURNING (next_seq - 1)::bigint AS assigned_seq
`

type NextDocumentNumberParams struct {
	TenantID uuid.UUID
	DocType  string
	Year     int32
}

// NextDocumentNumber atomically reserves the next gapless sequence value for a
// (tenant, doc_type, year) counter, creating the counter at 1 on first use
// (ADR-0010). The row is updated under the posting transaction, so the number is
// gapless as long as the transaction commits.
func (q *Queries) NextDocumentNumber(ctx context.Context, arg NextDocumentNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextDocumentNumber, arg.TenantID, arg.DocType, arg.Year)
	var assigned_seq int64
	err := row.Scan(&assigned_seq)
	return assigned_seq, err
}

const upsertStockLevel = `-- name: UpsertStockLevel :exec
INSERT INTO stock_levels (
    tenant_id, product_id, warehouse_id, batch_id, qty_on_hand, avg_cost, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, now()
)
ON CONFLICT (tenant_id, product_id, warehouse_id, batch_id) DO UPDATE
SET qty_on_hand = EXCLUDED.qty_on_hand,
    avg_cost = EXCLUDED.avg_cost,
    updated_at = now()
`

type UpsertStockLevelParams struct {
	TenantID    uuid.UUID
	ProductID   uuid.UUID
	WarehouseID uuid.UUID
	BatchID     pgtype.UUID
	QtyOnHand   pgtype.Numeric
	AvgCost     pgtype.Numeric
}

// UpsertStockLevel refreshes the derived cache for a key. Batch NULL is unique
// per key via UNIQUE NULLS NOT DISTINCT (migration 0004), so ON CONFLICT keys on
// the same four columns.
func (q *Queries) UpsertStockLevel(ctx context.Context, arg UpsertStockLevelParams) error {
	_, err := q.db.Exec(ctx, upsertStockLevel,
		arg.TenantID,
		arg.ProductID,
		arg.WarehouseID,
		arg.BatchID,
		arg.QtyOnHand,
		arg.AvgCost,
	)
	return err
}
