// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_uoms.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProductUom = `-- name: CreateProductUom :one
INSERT INTO product_uoms (tenant_id, product_id, uom, factor_to_base)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, product_id, uom, factor_to_base, created_at
`

type CreateProductUomParams struct {
	TenantID     uuid.UUID
	ProductID    uuid.UUID
	Uom          string
	FactorToBase pgtype.Numeric
}

func (q *Queries) CreateProductUom(ctx context.Context, arg CreateProductUomParams) (ProductUom, error) {
	row := q.db.QueryRow(ctx, createProductUom,
		arg.TenantID,
		arg.ProductID,
		arg.Uom,
		arg.FactorToBase,
	)
	var i ProductUom
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Uom,
		&i.FactorToBase,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProductUom = `-- name: DeleteProductUom :one
DELETE FROM product_uoms
WHERE tenant_id = $1 AND product_id = $2 AND id = $3
RETURNING id
`

type DeleteProductUomParams struct {
	TenantID  uuid.UUID
	ProductID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteProductUom(ctx context.Context, arg DeleteProductUomParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProductUom, arg.TenantID, arg.ProductID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listProductUoms = `-- name: ListProductUoms :many
SELECT id, tenant_id, product_id, uom, factor_to_base, created_at FROM product_uoms
WHERE tenant_id = $1 AND product_id = $2
ORDER BY uom
`

type ListProductUomsParams struct {
	TenantID  uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) ListProductUoms(ctx context.Context, arg ListProductUomsParams) ([]ProductUom, error) {
	rows, err := q.db.Query(ctx, listProductUoms, arg.TenantID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductUom
	for rows.Next() {
		var i ProductUom
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.Uom,
			&i.FactorToBase,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
