// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (tenant_id, sku, name, base_uom, is_batch_tracked, barcode)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, sku, name, base_uom, is_batch_tracked, barcode, status, created_at, updated_at
`

type CreateProductParams struct {
	TenantID       uuid.UUID
	Sku            string
	Name           string
	BaseUom        string
	IsBatchTracked bool
	Barcode        pgtype.Text
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.TenantID,
		arg.Sku,
		arg.Name,
		arg.BaseUom,
		arg.IsBatchTracked,
		arg.Barcode,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Sku,
		&i.Name,
		&i.BaseUom,
		&i.IsBatchTracked,
		&i.Barcode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, tenant_id, sku, name, base_uom, is_batch_tracked, barcode, status, created_at, updated_at FROM products
WHERE tenant_id = $1 AND id = $2
`

type GetProductParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.TenantID, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Sku,
		&i.Name,
		&i.BaseUom,
		&i.IsBatchTracked,
		&i.Barcode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, tenant_id, sku, name, base_uom, is_batch_tracked, barcode, status, created_at, updated_at FROM products
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL
       OR name ILIKE '%' || $3 || '%'
       OR sku  ILIKE '%' || $3 || '%')
ORDER BY
  CASE WHEN $3::text IS NOT NULL
       THEN -GREATEST(similarity(name, $3::text), similarity(sku, $3::text))
  END NULLS LAST,
  sku
`

type ListProductsParams struct {
	TenantID uuid.UUID
	Status   pgtype.Text
	Q        pgtype.Text
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.TenantID, arg.Status, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Sku,
			&i.Name,
			&i.BaseUom,
			&i.IsBatchTracked,
			&i.Barcode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $3,
    base_uom = $4,
    is_batch_tracked = $5,
    barcode = $6,
    status = $7,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, sku, name, base_uom, is_batch_tracked, barcode, status, created_at, updated_at
`

type UpdateProductParams struct {
	TenantID       uuid.UUID
	ID             uuid.UUID
	Name           string
	BaseUom        string
	IsBatchTracked bool
	Barcode        pgtype.Text
	Status         string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.BaseUom,
		arg.IsBatchTracked,
		arg.Barcode,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Sku,
		&i.Name,
		&i.BaseUom,
		&i.IsBatchTracked,
		&i.Barcode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
