// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const stockCardMovements = `-- name: StockCardMovements :many
SELECT id,
       warehouse_id,
       batch_id,
       qty_base,
       unit_cost,
       movement_type,
       doc_type,
       doc_id,
       effective_at,
       seq,
       is_provisional
FROM stock_movements
WHERE tenant_id = $1
  AND product_id = $2
  AND ($3::uuid IS NULL OR warehouse_id = $3::uuid)
ORDER BY warehouse_id, batch_id NULLS FIRST, effective_at, seq
`

type StockCardMovementsParams struct {
	TenantID    uuid.UUID
	ProductID   uuid.UUID
	WarehouseID pgtype.UUID
}

type StockCardMovementsRow struct {
	ID            uuid.UUID
	WarehouseID   uuid.UUID
	BatchID       pgtype.UUID
	QtyBase       pgtype.Numeric
	UnitCost      pgtype.Numeric
	MovementType  string
	DocType       string
	DocID         uuid.UUID
	EffectiveAt   pgtype.Timestamptz
	Seq           int64
	IsProvisional bool
}

// StockCardMovements returns the journal for one product, optionally one
// warehouse, ordered per key by (warehouse, batch, effective_at, seq). The
// report handler folds each contiguous key run through the costing engine to
// derive the running balance (ADR-0002); the append-only journal is the sole
// source of truth (ADR-0001).
func (q *Queries) StockCardMovements(ctx context.Context, arg StockCardMovementsParams) ([]StockCardMovementsRow, error) {
	rows, err := q.db.Query(ctx, stockCardMovements, arg.TenantID, arg.ProductID, arg.WarehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockCardMovementsRow
	for rows.Next() {
		var i StockCardMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseID,
			&i.BatchID,
			&i.QtyBase,
			&i.UnitCost,
			&i.MovementType,
			&i.DocType,
			&i.DocID,
			&i.EffectiveAt,
			&i.Seq,
			&i.IsProvisional,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stockOnHand = `-- name: StockOnHand :many

SELECT sl.product_id,
       p.sku,
       p.name AS product_name,
       sl.warehouse_id,
       w.code AS warehouse_code,
       w.name AS warehouse_name,
       sl.batch_id,
       b.batch_no,
       sl.qty_on_hand,
       sl.avg_cost
FROM stock_levels sl
JOIN products p ON p.id = sl.product_id
JOIN warehouses w ON w.id = sl.warehouse_id
LEFT JOIN batches b ON b.id = sl.batch_id
WHERE sl.tenant_id = $1
  AND ($2::uuid IS NULL OR sl.warehouse_id = $2::uuid)
  AND ($3::uuid IS NULL OR sl.product_id = $3::uuid)
ORDER BY p.sku, w.code, b.batch_no NULLS FIRST
`

type StockOnHandParams struct {
	TenantID    uuid.UUID
	WarehouseID pgtype.UUID
	ProductID   pgtype.UUID
}

type StockOnHandRow struct {
	ProductID     uuid.UUID
	Sku           string
	ProductName   string
	WarehouseID   uuid.UUID
	WarehouseCode string
	WarehouseName string
	BatchID       pgtype.UUID
	BatchNo       pgtype.Text
	QtyOnHand     pgtype.Numeric
	AvgCost       pgtype.Numeric
}

// Report queries (Track D - docs/plans/m1-parallel.md). All read-only over the
// existing tables and tenant-scoped through tenantTx + RLS. Stock on hand and
// valuation read the derived stock_levels cache; the stock card reads the
// append-only journal so the costing engine can fold a running balance.
// StockOnHand returns every cached level for the tenant, joined to product and
// warehouse (and batch, where tracked), optionally narrowed to one warehouse
// and/or product. NULLs on the filter args mean "no filter". Rows are ordered
// deterministically so report output is stable for golden files.
func (q *Queries) StockOnHand(ctx context.Context, arg StockOnHandParams) ([]StockOnHandRow, error) {
	rows, err := q.db.Query(ctx, stockOnHand, arg.TenantID, arg.WarehouseID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockOnHandRow
	for rows.Next() {
		var i StockOnHandRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Sku,
			&i.ProductName,
			&i.WarehouseID,
			&i.WarehouseCode,
			&i.WarehouseName,
			&i.BatchID,
			&i.BatchNo,
			&i.QtyOnHand,
			&i.AvgCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
