// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, expires_at)
VALUES ($1, $2)
RETURNING id, user_id, active_tenant_id, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveTenantID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, active_tenant_id, expires_at, created_at FROM sessions
WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveTenantID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const setSessionActiveTenant = `-- name: SetSessionActiveTenant :exec
UPDATE sessions
SET active_tenant_id = $2
WHERE id = $1
`

type SetSessionActiveTenantParams struct {
	ID             uuid.UUID
	ActiveTenantID pgtype.UUID
}

func (q *Queries) SetSessionActiveTenant(ctx context.Context, arg SetSessionActiveTenantParams) error {
	_, err := q.db.Exec(ctx, setSessionActiveTenant, arg.ID, arg.ActiveTenantID)
	return err
}
