// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (user_id, tenant_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, tenant_id, role, created_at
`

type CreateMembershipParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	Role     string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.UserID, arg.TenantID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, legal_name, costing_method, fiscal_year_start_month, active)
VALUES ($1, $2, $3, $4, true)
RETURNING id, name, legal_name, costing_method, fiscal_year_start_month, active, created_at, updated_at
`

type CreateTenantParams struct {
	Name                 string
	LegalName            string
	CostingMethod        string
	FiscalYearStartMonth int32
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.LegalName,
		arg.CostingMethod,
		arg.FiscalYearStartMonth,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LegalName,
		&i.CostingMethod,
		&i.FiscalYearStartMonth,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses (tenant_id, code, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, code, name, created_at, updated_at
`

type CreateWarehouseParams struct {
	TenantID uuid.UUID
	Code     string
	Name     string
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, createWarehouse, arg.TenantID, arg.Code, arg.Name)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, legal_name, costing_method, fiscal_year_start_month, active, created_at, updated_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LegalName,
		&i.CostingMethod,
		&i.FiscalYearStartMonth,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = $2,
    legal_name = $3,
    fiscal_year_start_month = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, legal_name, costing_method, fiscal_year_start_month, active, created_at, updated_at
`

type UpdateTenantParams struct {
	ID                   uuid.UUID
	Name                 string
	LegalName            string
	FiscalYearStartMonth int32
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.LegalName,
		arg.FiscalYearStartMonth,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LegalName,
		&i.CostingMethod,
		&i.FiscalYearStartMonth,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
