// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warehouses.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getWarehouse = `-- name: GetWarehouse :one
SELECT id, tenant_id, code, name, created_at, updated_at FROM warehouses
WHERE tenant_id = $1 AND id = $2
`

type GetWarehouseParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetWarehouse(ctx context.Context, arg GetWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, getWarehouse, arg.TenantID, arg.ID)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWarehouses = `-- name: ListWarehouses :many

SELECT id, tenant_id, code, name, created_at, updated_at FROM warehouses
WHERE tenant_id = $1
ORDER BY code
`

// CreateWarehouse lives in tenants.sql (used by onboarding); the list/get/update
// queries below round out warehouse management for the catalog track.
func (q *Queries) ListWarehouses(ctx context.Context, tenantID uuid.UUID) ([]Warehouse, error) {
	rows, err := q.db.Query(ctx, listWarehouses, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Warehouse
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarehouse = `-- name: UpdateWarehouse :one
UPDATE warehouses
SET code = $3,
    name = $4,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, code, name, created_at, updated_at
`

type UpdateWarehouseParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	Code     string
	Name     string
}

func (q *Queries) UpdateWarehouse(ctx context.Context, arg UpdateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, updateWarehouse,
		arg.TenantID,
		arg.ID,
		arg.Code,
		arg.Name,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
