//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CostingMethod.
const (
	Fifo            CostingMethod = "fifo"
	WeightedAverage CostingMethod = "weightedAverage"
)

// Valid indicates whether the value is a known member of the CostingMethod enum.
func (e CostingMethod) Valid() bool {
	switch e {
	case Fifo:
		return true
	case WeightedAverage:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin     Role = "admin"
	Owner     Role = "owner"
	Sales     Role = "sales"
	Viewer    Role = "viewer"
	Warehouse Role = "warehouse"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Owner:
		return true
	case Sales:
		return true
	case Viewer:
		return true
	case Warehouse:
		return true
	default:
		return false
	}
}

// Defines values for StockCardEntryMovementType.
const (
	Adjustment     StockCardEntryMovementType = "adjustment"
	CostCorrection StockCardEntryMovementType = "cost_correction"
	Issue          StockCardEntryMovementType = "issue"
	Opname         StockCardEntryMovementType = "opname"
	Receipt        StockCardEntryMovementType = "receipt"
	Revaluation    StockCardEntryMovementType = "revaluation"
	TransferIn     StockCardEntryMovementType = "transfer_in"
	TransferOut    StockCardEntryMovementType = "transfer_out"
)

// Valid indicates whether the value is a known member of the StockCardEntryMovementType enum.
func (e StockCardEntryMovementType) Valid() bool {
	switch e {
	case Adjustment:
		return true
	case CostCorrection:
		return true
	case Issue:
		return true
	case Opname:
		return true
	case Receipt:
		return true
	case Revaluation:
		return true
	case TransferIn:
		return true
	case TransferOut:
		return true
	default:
		return false
	}
}

// CostingMethod Locked at onboarding; switchable only at a fiscal year boundary (ADR-0002)
type CostingMethod string

// CreateInviteRequest defines model for CreateInviteRequest.
type CreateInviteRequest struct {
	Role Role `json:"role"`
}

// CreateTenantRequest defines model for CreateTenantRequest.
type CreateTenantRequest struct {
	// CostingMethod Locked at onboarding; switchable only at a fiscal year boundary (ADR-0002)
	CostingMethod        CostingMethod  `json:"costingMethod"`
	FiscalYearStartMonth *int           `json:"fiscalYearStartMonth,omitempty"`
	LegalName            *string        `json:"legalName,omitempty"`
	Name                 string         `json:"name"`
	Warehouse            WarehouseInput `json:"warehouse"`
}

// Error defines model for Error.
type Error struct {
	Code string `json:"code"`

	// Fields Per-field validation messages, when applicable
	Fields  *map[string]string `json:"fields,omitempty"`
	Message string             `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Invite defines model for Invite.
type Invite struct {
	ExpiresAt time.Time          `json:"expiresAt"`
	Id        openapi_types.UUID `json:"id"`
	Role      Role               `json:"role"`
	Token     string             `json:"token"`
}

// InvitePublic defines model for InvitePublic.
type InvitePublic struct {
	Role       Role   `json:"role"`
	TenantName string `json:"tenantName"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Member defines model for Member.
type Member struct {
	Email  openapi_types.Email `json:"email"`
	Name   string              `json:"name"`
	Role   Role                `json:"role"`
	UserId openapi_types.UUID  `json:"userId"`
}

// Membership defines model for Membership.
type Membership struct {
	Role   Role   `json:"role"`
	Tenant Tenant `json:"tenant"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// Role defines model for Role.
type Role string

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	// ActiveTenantId Absent until a tenant is selected
	ActiveTenantId *openapi_types.UUID `json:"activeTenantId,omitempty"`
	Memberships    []Membership        `json:"memberships"`
	User           User                `json:"user"`
}

// StockCardEntry defines model for StockCardEntry.
type StockCardEntry struct {
	// BatchId Absent for stock that is not batch-tracked
	BatchId      *openapi_types.UUID        `json:"batchId,omitempty"`
	DocId        *openapi_types.UUID        `json:"docId,omitempty"`
	DocType      *string                    `json:"docType,omitempty"`
	EffectiveAt  time.Time                  `json:"effectiveAt"`
	MovementId   openapi_types.UUID         `json:"movementId"`
	MovementType StockCardEntryMovementType `json:"movementType"`

	// Provisional True when the movement was valued below zero stock (D6)
	Provisional bool `json:"provisional"`

	// Qty Signed movement quantity in base units, as a decimal string
	Qty string `json:"qty"`

	// RunningQty On-hand quantity after this movement, as a decimal string
	RunningQty string `json:"runningQty"`

	// RunningValue Total stock value after this movement, as a decimal string
	RunningValue string `json:"runningValue"`
	Seq          int64  `json:"seq"`

	// UnitCost Cost booked for this movement by the costing engine, as a decimal string
	UnitCost    string             `json:"unitCost"`
	WarehouseId openapi_types.UUID `json:"warehouseId"`
}

// StockCardEntryMovementType defines model for StockCardEntry.MovementType.
type StockCardEntryMovementType string

// StockCardReport defines model for StockCardReport.
type StockCardReport struct {
	Entries   []StockCardEntry   `json:"entries"`
	ProductId openapi_types.UUID `json:"productId"`
}

// StockOnHandReport defines model for StockOnHandReport.
type StockOnHandReport struct {
	Rows []StockOnHandRow `json:"rows"`
}

// StockOnHandRow defines model for StockOnHandRow.
type StockOnHandRow struct {
	// BatchId Absent for stock that is not batch-tracked
	BatchId     *openapi_types.UUID `json:"batchId,omitempty"`
	BatchNo     *string             `json:"batchNo,omitempty"`
	ProductId   openapi_types.UUID  `json:"productId"`
	ProductName string              `json:"productName"`

	// QtyOnHand On-hand quantity in base units, as a decimal string
	QtyOnHand     string             `json:"qtyOnHand"`
	Sku           string             `json:"sku"`
	WarehouseCode string             `json:"warehouseCode"`
	WarehouseId   openapi_types.UUID `json:"warehouseId"`
	WarehouseName string             `json:"warehouseName"`
}

// StockValuationReport defines model for StockValuationReport.
type StockValuationReport struct {
	Rows []StockValuationRow `json:"rows"`

	// TotalValue Sum of value across all rows, as a decimal string
	TotalValue string `json:"totalValue"`
}

// StockValuationRow defines model for StockValuationRow.
type StockValuationRow struct {
	// AvgCost Weighted-average unit cost, as a decimal string
	AvgCost string `json:"avgCost"`

	// BatchId Absent for stock that is not batch-tracked
	BatchId     *openapi_types.UUID `json:"batchId,omitempty"`
	BatchNo     *string             `json:"batchNo,omitempty"`
	ProductId   openapi_types.UUID  `json:"productId"`
	ProductName string              `json:"productName"`

	// QtyOnHand On-hand quantity in base units, as a decimal string
	QtyOnHand string `json:"qtyOnHand"`
	Sku       string `json:"sku"`

	// Value qtyOnHand * avgCost, as a decimal string
	Value         string             `json:"value"`
	WarehouseCode string             `json:"warehouseCode"`
	WarehouseId   openapi_types.UUID `json:"warehouseId"`
	WarehouseName string             `json:"warehouseName"`
}

// SwitchTenantRequest defines model for SwitchTenantRequest.
type SwitchTenantRequest struct {
	TenantId openapi_types.UUID `json:"tenantId"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// TenantProfile defines model for TenantProfile.
type TenantProfile struct {
	// CostingMethod Locked at onboarding; switchable only at a fiscal year boundary (ADR-0002)
	CostingMethod        CostingMethod      `json:"costingMethod"`
	FiscalYearStartMonth int                `json:"fiscalYearStartMonth"`
	Id                   openapi_types.UUID `json:"id"`
	LegalName            string             `json:"legalName"`
	MyRole               Role               `json:"myRole"`
	Name                 string             `json:"name"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	Role Role `json:"role"`
}

// UpdateTenantRequest defines model for UpdateTenantRequest.
type UpdateTenantRequest struct {
	FiscalYearStartMonth *int    `json:"fiscalYearStartMonth,omitempty"`
	LegalName            *string `json:"legalName,omitempty"`
	Name                 *string `json:"name,omitempty"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Name  string              `json:"name"`
}

// WarehouseInput defines model for WarehouseInput.
type WarehouseInput struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// ProductFilter defines model for ProductFilter.
type ProductFilter = openapi_types.UUID

// WarehouseFilter defines model for WarehouseFilter.
type WarehouseFilter = openapi_types.UUID

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// ReportStockCardParams defines parameters for ReportStockCard.
type ReportStockCardParams struct {
	ProductId   openapi_types.UUID `form:"productId" json:"productId"`
	WarehouseId *WarehouseFilter   `form:"warehouseId,omitempty" json:"warehouseId,omitempty"`
}

// ReportStockOnHandParams defines parameters for ReportStockOnHand.
type ReportStockOnHandParams struct {
	WarehouseId *WarehouseFilter `form:"warehouseId,omitempty" json:"warehouseId,omitempty"`
	ProductId   *ProductFilter   `form:"productId,omitempty" json:"productId,omitempty"`
}

// ReportStockValuationParams defines parameters for ReportStockValuation.
type ReportStockValuationParams struct {
	WarehouseId *WarehouseFilter `form:"warehouseId,omitempty" json:"warehouseId,omitempty"`
	ProductId   *ProductFilter   `form:"productId,omitempty" json:"productId,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// SwitchTenantJSONRequestBody defines body for SwitchTenant for application/json ContentType.
type SwitchTenantJSONRequestBody = SwitchTenantRequest

// UpdateTenantJSONRequestBody defines body for UpdateTenant for application/json ContentType.
type UpdateTenantJSONRequestBody = UpdateTenantRequest

// CreateInviteJSONRequestBody defines body for CreateInvite for application/json ContentType.
type CreateInviteJSONRequestBody = CreateInviteRequest

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = UpdateMemberRequest

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = CreateTenantRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Authenticate and start a session
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout End the current session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Register Create a user account
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// GetSession Current user, memberships, and active tenant
	// (GET /auth/session)
	GetSession(w http.ResponseWriter, r *http.Request)
	// SwitchTenant Change the session's active tenant
	// (POST /auth/switch-tenant)
	SwitchTenant(w http.ResponseWriter, r *http.Request)
	// GetHealth Liveness check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetInvite Public invite details for the landing page
	// (GET /invites/{token})
	GetInvite(w http.ResponseWriter, r *http.Request, token string)
	// AcceptInvite Join the inviting tenant with the invite's role
	// (POST /invites/{token}/accept)
	AcceptInvite(w http.ResponseWriter, r *http.Request, token string)
	// ReportStockCard Per-product movement history with a running balance
	// (GET /reports/stock-card)
	ReportStockCard(w http.ResponseWriter, r *http.Request, params ReportStockCardParams)
	// ReportStockOnHand Current on-hand quantity per product, warehouse, and batch
	// (GET /reports/stock-on-hand)
	ReportStockOnHand(w http.ResponseWriter, r *http.Request, params ReportStockOnHandParams)
	// ReportStockValuation Monetary value of stock per product and warehouse
	// (GET /reports/stock-valuation)
	ReportStockValuation(w http.ResponseWriter, r *http.Request, params ReportStockValuationParams)
	// GetTenant Profile of the session's active tenant
	// (GET /tenant)
	GetTenant(w http.ResponseWriter, r *http.Request)
	// UpdateTenant Update tenant profile (owner only)
	// (PATCH /tenant)
	UpdateTenant(w http.ResponseWriter, r *http.Request)
	// ListInvites List open invites (owner or admin)
	// (GET /tenant/invites)
	ListInvites(w http.ResponseWriter, r *http.Request)
	// CreateInvite Create a shareable invite link (owner or admin)
	// (POST /tenant/invites)
	CreateInvite(w http.ResponseWriter, r *http.Request)
	// RevokeInvite Revoke an invite (owner or admin)
	// (DELETE /tenant/invites/{inviteId})
	RevokeInvite(w http.ResponseWriter, r *http.Request, inviteId openapi_types.UUID)
	// ListMembers List tenant members
	// (GET /tenant/members)
	ListMembers(w http.ResponseWriter, r *http.Request)
	// RemoveMember Remove a member (owner only)
	// (DELETE /tenant/members/{userId})
	RemoveMember(w http.ResponseWriter, r *http.Request, userId openapi_types.UUID)
	// UpdateMember Change a member's role (owner only)
	// (PATCH /tenant/members/{userId})
	UpdateMember(w http.ResponseWriter, r *http.Request, userId openapi_types.UUID)
	// CreateTenant Onboard a new tenant with its first warehouse; creator becomes owner
	// (POST /tenants)
	CreateTenant(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SwitchTenant operation middleware
func (siw *ServerInterfaceWrapper) SwitchTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SwitchTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInvite operation middleware
func (siw *ServerInterfaceWrapper) GetInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token" -------------
	var token string

	err = runtime.BindStyledParameterWithOptions("simple", "token", r.PathValue("token"), &token, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInvite(w, r, token)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptInvite operation middleware
func (siw *ServerInterfaceWrapper) AcceptInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token" -------------
	var token string

	err = runtime.BindStyledParameterWithOptions("simple", "token", r.PathValue("token"), &token, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptInvite(w, r, token)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportStockCard operation middleware
func (siw *ServerInterfaceWrapper) ReportStockCard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ReportStockCardParams

	// ------------- Required query parameter "productId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "productId", r.URL.Query(), &params.ProductId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "productId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "warehouseId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "warehouseId", r.URL.Query(), &params.WarehouseId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "warehouseId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "warehouseId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportStockCard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportStockOnHand operation middleware
func (siw *ServerInterfaceWrapper) ReportStockOnHand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ReportStockOnHandParams

	// ------------- Optional query parameter "warehouseId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "warehouseId", r.URL.Query(), &params.WarehouseId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "warehouseId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "warehouseId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "productId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "productId", r.URL.Query(), &params.ProductId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "productId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportStockOnHand(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportStockValuation operation middleware
func (siw *ServerInterfaceWrapper) ReportStockValuation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ReportStockValuationParams

	// ------------- Optional query parameter "warehouseId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "warehouseId", r.URL.Query(), &params.WarehouseId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "warehouseId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "warehouseId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "productId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "productId", r.URL.Query(), &params.ProductId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "productId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportStockValuation(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTenant operation middleware
func (siw *ServerInterfaceWrapper) GetTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTenant operation middleware
func (siw *ServerInterfaceWrapper) UpdateTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInvites operation middleware
func (siw *ServerInterfaceWrapper) ListInvites(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInvites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInvite operation middleware
func (siw *ServerInterfaceWrapper) CreateInvite(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInvite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeInvite operation middleware
func (siw *ServerInterfaceWrapper) RevokeInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "inviteId" -------------
	var inviteId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "inviteId", r.PathValue("inviteId"), &inviteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "inviteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeInvite(w, r, inviteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMembers operation middleware
func (siw *ServerInterfaceWrapper) ListMembers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMembers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveMember(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMember(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTenant operation middleware
func (siw *ServerInterfaceWrapper) CreateTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/register", wrapper.Register)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/session", wrapper.GetSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/switch-tenant", wrapper.SwitchTenant)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/invites/{token}", wrapper.GetInvite)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/invites/{token}/accept", wrapper.AcceptInvite)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/reports/stock-card", wrapper.ReportStockCard)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/reports/stock-on-hand", wrapper.ReportStockOnHand)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/reports/stock-valuation", wrapper.ReportStockValuation)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tenant", wrapper.GetTenant)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/tenant", wrapper.UpdateTenant)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tenant/invites", wrapper.ListInvites)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tenant/invites", wrapper.CreateInvite)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/tenant/invites/{inviteId}", wrapper.RevokeInvite)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tenant/members", wrapper.ListMembers)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/tenant/members/{userId}", wrapper.RemoveMember)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/tenant/members/{userId}", wrapper.UpdateMember)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tenants", wrapper.CreateTenant)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fx7c9u4Ef8qO2hnzu5Qlp3L3EyVv1xf7s5tnKRxkptOmslA5EpETAI0AErRZfTdO3iQIilQj9iyr9f+",
	"J0sg9oHfPrC79FcSi7wQHLlWZPSVFFTSHDVK+9drKZIy1j+xTKM0XzBORuS2RLkgEeE0RzIihVt0mZCI",
	"qDjFnJqVEyFzqsmIlCUzv+hFYRYrLRmfkuUyIr9SiakoFW7efl4t25PAMiISVSG4QivLheCTjMXafI4F",
	"18jtR1oUGYupZoIPPyvBzXcrIn+WOCEj8qfhSktD96saPpdSSEcoQRVLVphNyIi8QSVKGSPQTCJNFoBf",
	"mNKKLCPyk5BjliTID8/FealT5NrsigmMSw1caChQ5kxrTAw37zgtdSok+w2TwzP0UmigTaYMC+9pxhJL",
	"xj33AIdzW6LSMKEswwRmNX2LSf+4w4vSjE+vUKfCaqe9zwsR32ACVIPgY0Flwvj0Gag503FKxxmC4NnC",
	"/ExhwlRMM1gglTAWJU+oXMDR+Y9vBqenp0+OSUSQlzkZfSBzZNNUY3I+Q0mnSCIyYRNBPq6hOyIXEqnG",
	"Sz5jGr1M1n6lKFBq5jAvRYbbNPXGrHHWclsyaZDwwT24IivGnzHWK7JvkVOue8nGXdVtot/W89KIbNT1",
	"L6TyWlOprwTXqdP/hJaZJqOziOT0C8uNzs6eRCRn3P9RM8y4xilKs12GU5q9tL7k67oauf8hZ/wF8qmh",
	"dBbQdu2EtklTO7VLXpR6Ta+WXNRRUHP7kM5ry+hqOQnLNGGYJXYJTRJm8Eqz161H1x5pY/s1yoHdpGEe",
	"kKNSdIoqgnmKHLxpjjMkAZb94gCtjkKsEKv1IfF/QZo5BLTlV5rq0n6qzEfcBEylQ9A/FSLkjGmdEH4p",
	"mER1rlthJ6EaB5rlSAJ4YckOISrawz4josWNCxub5bOE7L7VI1FDgH6xX5fjjMV3cSER0dYt9Nhah8/G",
	"2qjf3bwQU8Z7/QzmlGUtRbtvApouqFJzIdvHUn+5DTTVtvUDIV6vMB+jvBOXvM9N7XMKpUJ5meyWgzWF",
	"9M9FlZOquOw9HCewSllxH7DZttrFnB4cbWLzDU6Z0ijvA0Y7hottaGs+fro3+DwbQVm92muPOOcoSURo",
	"kjPeCjQRUTRDRSIyYzhHGUwyrlEpJvgln4h1tdFYs5lPBS4DGdL5WCHXUHLNMqDgDgqYAoUZxib/i7Z7",
	"yLzGmKXJNOZqG1IauFzWW1Ip6aIyj207vDNrQvZB2hyFjuBai/jmgsrkOddysa62MdVxukFfEyFBmT1A",
	"p9Tqy+Tt9qmBltRknbsoLhHx5W5BKBHxW/tdwO/gZIL2mPcJfrmYYY4VKLYfsV9eMVFhV2KMrDCmzZQq",
	"LSVJuZqg/GSxXP8lSm0h/rlU2mxEIiKKRqb1KRZSGjGEeUzijGalS/lDmC+kmDFlk6b1M3orS3T5j04R",
	"Ks5hTpVJlUpz0cJMzOE3lMKf4tGPPxyvxB4LkSHlhtCtXqwTuGZTjslq59uScs30AhiHMVUIJWdaRUAV",
	"UEgwZjnNwDMfSjBKzhmf/jNE6hUfpJQnKxJ0olGCTpmq6e9L6L1RQkBtQtunjT6snu5ES+FtC1iM6x+e",
	"klDub5Rl7hfrHJlvYSyEucMZi2txAuOFPV+fpgPyKeO4M3/NisXeUbhhPFGn9tEyFIefhohtY3VaagGg",
	"c0htpG/0ZG+wEDIUOLmW/uNOjrnjGgPOeVVL2ltxzTJUxVivVK/4L5T3yiXFfE+h/H5ivi7U2s16vp0v",
	"MX+0uGEfeCmC0WCf06lX9169b/XCibuDa/o276duyiDl2qwu+q7Q+5lwY/1ul59WyfSmJG1lde2+zW6X",
	"WFORvbh6X4W8+4P8assQ6s3lU9OsJx5clzmISRUKYimUApplYLjY8XRDZtUiuoMuQmZGZ9NwxPjV1+YG",
	"1BXnLBZtiNgZj/834Xsz4VkYWDVD8BfwJ7l/2P6jeYWoBnWlt6Bt2NL1lsqubtz29gvP9ZMh2m/rCkCb",
	"3I5lNL6TetnGm7Nj4bUUE5bhQ5W01zPWHSXeXNTOF2/2KL/sq70m9fVSdlDUmqWQ5t8V5jbpLu0P2Mlw",
	"ZLfgve/gHrb/sAyxr+5Ya7x/26pI9dpYpznS29HYUl3bVWeBPkMPa/ZSGZeS6cW1AZNvMLjq14UQNwzr",
	"9nTs/qz704pxTT/5tSsN0oL9AxeuA8l8/awdq67KTLNBVRbjM+RayAXklNOpu4aafOCSJ4KjYpTD9dVz",
	"SJgRcFxqIdUJXAhu8gI9mDCp9MjdYo0DM7mDucEqxqcZgu9HiwloWerUbjwWOrVrfhagUM5QwpGgBRsY",
	"VU2RH4MJo2aBuW9eW8Yhzphh7EgUyM1aI6yT6dhyY4RggqsRxDTH7MIEfNeOiuAGx3Q8iM1XRVZKmkFB",
	"daoiGM7OoJA4YV/gKBGxGl68evn++cu3l69eXp/kyfHJv61emTYugFwbfcP560sTzVAqp8zTk7OTUwMO",
	"zxkZke9PTk++t3VTndrzHNJSp8NMTJntoxQ+zTMItPmgCWuu40AceFDpv4lkcW9N6VY3Y9mGqJYldkcW",
	"npye3hvtZik30Bb3P4Mybg4TOPKABgd3UKiPjXqfnp71UapZH7bmCprGRUYfPkZElXlO5aIzo2DhZskD",
	"hcqczMP1sQnvM/rOzdUBOxp8Grh9eNGQJ24I4RuFqsV47g0lLqU05rHOvfQ9iH7+qy7FgaDXbYLshL6z",
	"eyPvC+rrQypxLEquIbZjBf4w/rr9MOphHvPAkyfbH+jOmWxCpZtxAAqlQgnUsdg4zOp4R1/JFANH+TPq",
	"6zocPJZBX3SxeHeYV1satUTQ6INE1nZdP8j3eZrqsheLwarLFzaA5v3jQEYQuuL8vtzweVOHEKeUT7/Z",
	"RZmHvt/+0GokrXPalrjLIhzT36nQGaf1eEafMfgBjgNq1VMIxjU5Y7HNh8pio9W/YDPkqBTEKcY3TjZm",
	"RyPU8KudpFhuEtIPjxxQyNacRkBU9zskqCnLlDv/p4cfqHvHb7iYcxASJM5sQ8WpzXJwdnp4Drzgbspl",
	"c8LhtOcZrFTlG0AIGeUJ41Mo6BRdG381DPvBp/8mm1wl/9WETduBNMdUu9eSjwFcDWkcY6G787f3RjLq",
	"cbnnluzhkbvF6f1dMI7Js8rrWR9jh1brxtzdgtj/tCHU0Ddatii3TBmYe33Pmb8IOm6/UyCrQspQ2naB",
	"Gtqq9CCmbqTF+8BOjzdFEDJBiQl8FqXkNLMHKDiCr2Oae6MbR8wW9vu6ZnkcAdI4XXVgYyrlwjKZIvi+",
	"JYhOTTmqOrjNUjxP6vWuv2B2cKJ+pzotXUhQshkqoNqV3AvBuD6BtwZ01RXaFuRpmTANWlKWPQPmavNo",
	"7swS55Jpjbye6D3zF9Zufm80WXdASdi7bBit77f3rYXYMJxW9IfdUXzjMg7nDTpt5QCQryoYpEzZokjl",
	"ob1CHiwjusvtYhV0UA4qC8i7klnrozVkxzSjPA5an0f/RgN0eE48aDOcoTNCA9UFHHkuopXhRa69dAw3",
	"WPPCBR/YAZZCKDs+HIFEmsBEinxlEp/s7gpiGqd4Ag45dvJ9vFjtb+xxKGR1cFsso25YdGxjX/huR3z7",
	"zZbD4701cBBAfNUuk2K+ykc62faj3AL8na/reqHA+lBbcDKLLKRCEF5NXm0CsXPbYuJRLDhY0obiFgRH",
	"YIQrTe5AFdzqxSfBP6V1O/CT8f6bYAwlT1CGI0ZuOxxwVL2jAVUfmHG4Ojs2QQP9LkwBhQllOp2UGUg0",
	"HDPBbf01xTo65pRxTU3uA3aWjcZ1cLShyNKNQAmXBOFtSW2ymiVVYKx20qkU5TQNDC1tMbi6F/5HtLnu",
	"0EPA7OolvzvDuxIcNZWLrjU07M7a2mqi19rbqsrSd1FtVFgOpPx2K3VrlaOoFj6Gmj2XlWn2VjpsGyFO",
	"1zXabCMeqGwV6lQ+cNlq65E6HpPHOtN7ydOcDB0R4MjO0NvX+Y6bNlZd4ntt7QVT/m6t7mptO01lXdaX",
	"zc4A4nqyUSCHiv1HMTujGxANNmo1S7DvKthmU7hq0Xzz8UAWF3q58oE7JtVp9t7yWy2TB08LqxaJSqlE",
	"m/X7mlrG+E3gMNftZvjVfbhMli4NzNC9fNdNVmbiBvtqVIHunlePL8E8jnoc00AreIfRvbXUVynoTrf/",
	"jw3V+57NRpfl3555EJflX5nbwWV5rqo4/TtI0KwL87Gi0utyXdfDr+69ui0gz8XMj0DtBHK3FKR9LnnI",
	"MLtfd7ZjFYZboF5dnci6i0HUryjewRy2ZHKNQzhUJtcedXvgTK4yuf4ULq+N8r8AU75LWWHKF697kzbV",
	"339u/meDg6YV35DInz1cIv/Wt55ddrFq7N9zQ+bu2for9283gALHeauXwbQCOxC3uhw/cwIJCWOMRY4K",
	"3Juxy06zcG3o78NH4zHcfJxzS6XMyIgMZ2dk+XH5nwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
