//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CatalogStatus.
const (
	Active   CatalogStatus = "active"
	Archived CatalogStatus = "archived"
)

// Valid indicates whether the value is a known member of the CatalogStatus enum.
func (e CatalogStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Archived:
		return true
	default:
		return false
	}
}

// Defines values for CostingMethod.
const (
	Fifo            CostingMethod = "fifo"
	WeightedAverage CostingMethod = "weightedAverage"
)

// Valid indicates whether the value is a known member of the CostingMethod enum.
func (e CostingMethod) Valid() bool {
	switch e {
	case Fifo:
		return true
	case WeightedAverage:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAdmin     Role = "admin"
	RoleOwner     Role = "owner"
	RoleSales     Role = "sales"
	RoleViewer    Role = "viewer"
	RoleWarehouse Role = "warehouse"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleOwner:
		return true
	case RoleSales:
		return true
	case RoleViewer:
		return true
	case RoleWarehouse:
		return true
	default:
		return false
	}
}

// Defines values for ListPartnersParamsRole.
const (
	Customer ListPartnersParamsRole = "customer"
	Supplier ListPartnersParamsRole = "supplier"
)

// Valid indicates whether the value is a known member of the ListPartnersParamsRole enum.
func (e ListPartnersParamsRole) Valid() bool {
	switch e {
	case Customer:
		return true
	case Supplier:
		return true
	default:
		return false
	}
}

// Batch defines model for Batch.
type Batch struct {
	BatchNo string `json:"batchNo"`

	// ExpiryDate Optional expiry date
	ExpiryDate *openapi_types.Date `json:"expiryDate,omitempty"`
	Id         openapi_types.UUID  `json:"id"`
	ProductId  openapi_types.UUID  `json:"productId"`
}

// CatalogStatus defines model for CatalogStatus.
type CatalogStatus string

// CostingMethod Locked at onboarding; switchable only at a fiscal year boundary (ADR-0002)
type CostingMethod string

// CreateBatchRequest defines model for CreateBatchRequest.
type CreateBatchRequest struct {
	BatchNo    string              `json:"batchNo"`
	ExpiryDate *openapi_types.Date `json:"expiryDate,omitempty"`
}

// CreateInviteRequest defines model for CreateInviteRequest.
type CreateInviteRequest struct {
	Role Role `json:"role"`
}

// CreatePartnerRequest defines model for CreatePartnerRequest.
type CreatePartnerRequest struct {
	Code       *string `json:"code,omitempty"`
	IsCustomer *bool   `json:"isCustomer,omitempty"`
	IsSupplier *bool   `json:"isSupplier,omitempty"`
	Name       string  `json:"name"`
}

// CreateProductRequest defines model for CreateProductRequest.
type CreateProductRequest struct {
	Barcode        *string `json:"barcode,omitempty"`
	BaseUom        string  `json:"baseUom"`
	IsBatchTracked *bool   `json:"isBatchTracked,omitempty"`
	Name           string  `json:"name"`
	Sku            string  `json:"sku"`
}

// CreateProductUomRequest defines model for CreateProductUomRequest.
type CreateProductUomRequest struct {
	// FactorToBase Positive decimal factor to the base unit
	FactorToBase string `json:"factorToBase"`
	Uom          string `json:"uom"`
}

// CreateTenantRequest defines model for CreateTenantRequest.
type CreateTenantRequest struct {
	// CostingMethod Locked at onboarding; switchable only at a fiscal year boundary (ADR-0002)
	CostingMethod        CostingMethod  `json:"costingMethod"`
	FiscalYearStartMonth *int           `json:"fiscalYearStartMonth,omitempty"`
	LegalName            *string        `json:"legalName,omitempty"`
	Name                 string         `json:"name"`
	Warehouse            WarehouseInput `json:"warehouse"`
}

// Error defines model for Error.
type Error struct {
	Code string `json:"code"`

	// Fields Per-field validation messages, when applicable
	Fields  *map[string]string `json:"fields,omitempty"`
	Message string             `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Invite defines model for Invite.
type Invite struct {
	ExpiresAt time.Time          `json:"expiresAt"`
	Id        openapi_types.UUID `json:"id"`
	Role      Role               `json:"role"`
	Token     string             `json:"token"`
}

// InvitePublic defines model for InvitePublic.
type InvitePublic struct {
	Role       Role   `json:"role"`
	TenantName string `json:"tenantName"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Member defines model for Member.
type Member struct {
	Email  openapi_types.Email `json:"email"`
	Name   string              `json:"name"`
	Role   Role                `json:"role"`
	UserId openapi_types.UUID  `json:"userId"`
}

// Membership defines model for Membership.
type Membership struct {
	Role   Role   `json:"role"`
	Tenant Tenant `json:"tenant"`
}

// Partner defines model for Partner.
type Partner struct {
	// Code Optional; unique within a tenant when present
	Code       *string            `json:"code,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	IsCustomer bool               `json:"isCustomer"`
	IsSupplier bool               `json:"isSupplier"`
	Name       string             `json:"name"`
	Status     CatalogStatus      `json:"status"`
}

// Product defines model for Product.
type Product struct {
	// Barcode Optional; unique within a tenant when present
	Barcode *string `json:"barcode,omitempty"`

	// BaseUom The unit a product's stock is counted in (glossary "Base unit")
	BaseUom        string             `json:"baseUom"`
	Id             openapi_types.UUID `json:"id"`
	IsBatchTracked bool               `json:"isBatchTracked"`
	Name           string             `json:"name"`
	Sku            string             `json:"sku"`
	Status         CatalogStatus      `json:"status"`
}

// ProductUom defines model for ProductUom.
type ProductUom struct {
	// FactorToBase Decimal factor to the base unit (carton = "24"); numeric, sent as string to preserve precision
	FactorToBase string             `json:"factorToBase"`
	Id           openapi_types.UUID `json:"id"`
	ProductId    openapi_types.UUID `json:"productId"`
	Uom          string             `json:"uom"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// Role defines model for Role.
type Role string

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	// ActiveTenantId Absent until a tenant is selected
	ActiveTenantId *openapi_types.UUID `json:"activeTenantId,omitempty"`
	Memberships    []Membership        `json:"memberships"`
	User           User                `json:"user"`
}

// SwitchTenantRequest defines model for SwitchTenantRequest.
type SwitchTenantRequest struct {
	TenantId openapi_types.UUID `json:"tenantId"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// TenantProfile defines model for TenantProfile.
type TenantProfile struct {
	// CostingMethod Locked at onboarding; switchable only at a fiscal year boundary (ADR-0002)
	CostingMethod        CostingMethod      `json:"costingMethod"`
	FiscalYearStartMonth int                `json:"fiscalYearStartMonth"`
	Id                   openapi_types.UUID `json:"id"`
	LegalName            string             `json:"legalName"`
	MyRole               Role               `json:"myRole"`
	Name                 string             `json:"name"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	Role Role `json:"role"`
}

// UpdatePartnerRequest Patch semantics; absent fields keep their current value
type UpdatePartnerRequest struct {
	// Code Empty string clears the code
	Code       *string        `json:"code,omitempty"`
	IsCustomer *bool          `json:"isCustomer,omitempty"`
	IsSupplier *bool          `json:"isSupplier,omitempty"`
	Name       *string        `json:"name,omitempty"`
	Status     *CatalogStatus `json:"status,omitempty"`
}

// UpdateProductRequest Patch semantics; absent fields keep their current value
type UpdateProductRequest struct {
	// Barcode Empty string clears the barcode
	Barcode        *string        `json:"barcode,omitempty"`
	BaseUom        *string        `json:"baseUom,omitempty"`
	IsBatchTracked *bool          `json:"isBatchTracked,omitempty"`
	Name           *string        `json:"name,omitempty"`
	Status         *CatalogStatus `json:"status,omitempty"`
}

// UpdateTenantRequest defines model for UpdateTenantRequest.
type UpdateTenantRequest struct {
	FiscalYearStartMonth *int    `json:"fiscalYearStartMonth,omitempty"`
	LegalName            *string `json:"legalName,omitempty"`
	Name                 *string `json:"name,omitempty"`
}

// UpdateWarehouseRequest Patch semantics; absent fields keep their current value
type UpdateWarehouseRequest struct {
	Code *string `json:"code,omitempty"`
	Name *string `json:"name,omitempty"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Name  string              `json:"name"`
}

// Warehouse defines model for Warehouse.
type Warehouse struct {
	Code string             `json:"code"`
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// WarehouseInput defines model for WarehouseInput.
type WarehouseInput struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// ProductId defines model for ProductId.
type ProductId = openapi_types.UUID

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// ListPartnersParams defines parameters for ListPartners.
type ListPartnersParams struct {
	// Role Filter to partners that are a supplier or a customer
	Role   *ListPartnersParamsRole `form:"role,omitempty" json:"role,omitempty"`
	Status *CatalogStatus          `form:"status,omitempty" json:"status,omitempty"`
}

// ListPartnersParamsRole defines parameters for ListPartners.
type ListPartnersParamsRole string

// ListProductsParams defines parameters for ListProducts.
type ListProductsParams struct {
	Status *CatalogStatus `form:"status,omitempty" json:"status,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// SwitchTenantJSONRequestBody defines body for SwitchTenant for application/json ContentType.
type SwitchTenantJSONRequestBody = SwitchTenantRequest

// CreatePartnerJSONRequestBody defines body for CreatePartner for application/json ContentType.
type CreatePartnerJSONRequestBody = CreatePartnerRequest

// UpdatePartnerJSONRequestBody defines body for UpdatePartner for application/json ContentType.
type UpdatePartnerJSONRequestBody = UpdatePartnerRequest

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = CreateProductRequest

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = UpdateProductRequest

// CreateBatchJSONRequestBody defines body for CreateBatch for application/json ContentType.
type CreateBatchJSONRequestBody = CreateBatchRequest

// CreateProductUomJSONRequestBody defines body for CreateProductUom for application/json ContentType.
type CreateProductUomJSONRequestBody = CreateProductUomRequest

// UpdateTenantJSONRequestBody defines body for UpdateTenant for application/json ContentType.
type UpdateTenantJSONRequestBody = UpdateTenantRequest

// CreateInviteJSONRequestBody defines body for CreateInvite for application/json ContentType.
type CreateInviteJSONRequestBody = CreateInviteRequest

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = UpdateMemberRequest

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = CreateTenantRequest

// CreateWarehouseJSONRequestBody defines body for CreateWarehouse for application/json ContentType.
type CreateWarehouseJSONRequestBody = WarehouseInput

// UpdateWarehouseJSONRequestBody defines body for UpdateWarehouse for application/json ContentType.
type UpdateWarehouseJSONRequestBody = UpdateWarehouseRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Authenticate and start a session
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout End the current session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Register Create a user account
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// GetSession Current user, memberships, and active tenant
	// (GET /auth/session)
	GetSession(w http.ResponseWriter, r *http.Request)
	// SwitchTenant Change the session's active tenant
	// (POST /auth/switch-tenant)
	SwitchTenant(w http.ResponseWriter, r *http.Request)
	// GetHealth Liveness check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetInvite Public invite details for the landing page
	// (GET /invites/{token})
	GetInvite(w http.ResponseWriter, r *http.Request, token string)
	// AcceptInvite Join the inviting tenant with the invite's role
	// (POST /invites/{token}/accept)
	AcceptInvite(w http.ResponseWriter, r *http.Request, token string)
	// ListPartners List partners in the active tenant
	// (GET /partners)
	ListPartners(w http.ResponseWriter, r *http.Request, params ListPartnersParams)
	// CreatePartner Create a partner
	// (POST /partners)
	CreatePartner(w http.ResponseWriter, r *http.Request)
	// GetPartner Get a partner
	// (GET /partners/{partnerId})
	GetPartner(w http.ResponseWriter, r *http.Request, partnerId openapi_types.UUID)
	// UpdatePartner Update a partner
	// (PATCH /partners/{partnerId})
	UpdatePartner(w http.ResponseWriter, r *http.Request, partnerId openapi_types.UUID)
	// ListProducts List products in the active tenant
	// (GET /products)
	ListProducts(w http.ResponseWriter, r *http.Request, params ListProductsParams)
	// CreateProduct Create a product
	// (POST /products)
	CreateProduct(w http.ResponseWriter, r *http.Request)
	// GetProduct Get a product
	// (GET /products/{productId})
	GetProduct(w http.ResponseWriter, r *http.Request, productId ProductId)
	// UpdateProduct Update a product
	// (PATCH /products/{productId})
	UpdateProduct(w http.ResponseWriter, r *http.Request, productId ProductId)
	// ListProductBatches List a product's batches
	// (GET /products/{productId}/batches)
	ListProductBatches(w http.ResponseWriter, r *http.Request, productId ProductId)
	// CreateBatch Create a batch for a batch-tracked product
	// (POST /products/{productId}/batches)
	CreateBatch(w http.ResponseWriter, r *http.Request, productId ProductId)
	// ListProductUoms List a product's unit conversions
	// (GET /products/{productId}/uoms)
	ListProductUoms(w http.ResponseWriter, r *http.Request, productId ProductId)
	// CreateProductUom Add a unit conversion to a product
	// (POST /products/{productId}/uoms)
	CreateProductUom(w http.ResponseWriter, r *http.Request, productId ProductId)
	// DeleteProductUom Remove a unit conversion
	// (DELETE /products/{productId}/uoms/{uomId})
	DeleteProductUom(w http.ResponseWriter, r *http.Request, productId ProductId, uomId openapi_types.UUID)
	// GetTenant Profile of the session's active tenant
	// (GET /tenant)
	GetTenant(w http.ResponseWriter, r *http.Request)
	// UpdateTenant Update tenant profile (owner only)
	// (PATCH /tenant)
	UpdateTenant(w http.ResponseWriter, r *http.Request)
	// ListInvites List open invites (owner or admin)
	// (GET /tenant/invites)
	ListInvites(w http.ResponseWriter, r *http.Request)
	// CreateInvite Create a shareable invite link (owner or admin)
	// (POST /tenant/invites)
	CreateInvite(w http.ResponseWriter, r *http.Request)
	// RevokeInvite Revoke an invite (owner or admin)
	// (DELETE /tenant/invites/{inviteId})
	RevokeInvite(w http.ResponseWriter, r *http.Request, inviteId openapi_types.UUID)
	// ListMembers List tenant members
	// (GET /tenant/members)
	ListMembers(w http.ResponseWriter, r *http.Request)
	// RemoveMember Remove a member (owner only)
	// (DELETE /tenant/members/{userId})
	RemoveMember(w http.ResponseWriter, r *http.Request, userId openapi_types.UUID)
	// UpdateMember Change a member's role (owner only)
	// (PATCH /tenant/members/{userId})
	UpdateMember(w http.ResponseWriter, r *http.Request, userId openapi_types.UUID)
	// CreateTenant Onboard a new tenant with its first warehouse; creator becomes owner
	// (POST /tenants)
	CreateTenant(w http.ResponseWriter, r *http.Request)
	// ListWarehouses List warehouses in the active tenant
	// (GET /warehouses)
	ListWarehouses(w http.ResponseWriter, r *http.Request)
	// CreateWarehouse Create a warehouse
	// (POST /warehouses)
	CreateWarehouse(w http.ResponseWriter, r *http.Request)
	// UpdateWarehouse Update a warehouse
	// (PATCH /warehouses/{warehouseId})
	UpdateWarehouse(w http.ResponseWriter, r *http.Request, warehouseId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SwitchTenant operation middleware
func (siw *ServerInterfaceWrapper) SwitchTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SwitchTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInvite operation middleware
func (siw *ServerInterfaceWrapper) GetInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token" -------------
	var token string

	err = runtime.BindStyledParameterWithOptions("simple", "token", r.PathValue("token"), &token, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInvite(w, r, token)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptInvite operation middleware
func (siw *ServerInterfaceWrapper) AcceptInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token" -------------
	var token string

	err = runtime.BindStyledParameterWithOptions("simple", "token", r.PathValue("token"), &token, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptInvite(w, r, token)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPartners operation middleware
func (siw *ServerInterfaceWrapper) ListPartners(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPartnersParams

	// ------------- Optional query parameter "role" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "role", r.URL.Query(), &params.Role, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "role"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "role", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPartners(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePartner operation middleware
func (siw *ServerInterfaceWrapper) CreatePartner(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePartner(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPartner operation middleware
func (siw *ServerInterfaceWrapper) GetPartner(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "partnerId" -------------
	var partnerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "partnerId", r.PathValue("partnerId"), &partnerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "partnerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPartner(w, r, partnerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePartner operation middleware
func (siw *ServerInterfaceWrapper) UpdatePartner(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "partnerId" -------------
	var partnerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "partnerId", r.PathValue("partnerId"), &partnerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "partnerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePartner(w, r, partnerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProducts operation middleware
func (siw *ServerInterfaceWrapper) ListProducts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProductsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProducts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProduct(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProduct operation middleware
func (siw *ServerInterfaceWrapper) GetProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", r.PathValue("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProduct(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProduct operation middleware
func (siw *ServerInterfaceWrapper) UpdateProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", r.PathValue("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProduct(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProductBatches operation middleware
func (siw *ServerInterfaceWrapper) ListProductBatches(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", r.PathValue("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProductBatches(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBatch operation middleware
func (siw *ServerInterfaceWrapper) CreateBatch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", r.PathValue("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBatch(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProductUoms operation middleware
func (siw *ServerInterfaceWrapper) ListProductUoms(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", r.PathValue("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProductUoms(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProductUom operation middleware
func (siw *ServerInterfaceWrapper) CreateProductUom(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", r.PathValue("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProductUom(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProductUom operation middleware
func (siw *ServerInterfaceWrapper) DeleteProductUom(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", r.PathValue("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	// ------------- Path parameter "uomId" -------------
	var uomId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uomId", r.PathValue("uomId"), &uomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uomId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProductUom(w, r, productId, uomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTenant operation middleware
func (siw *ServerInterfaceWrapper) GetTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTenant operation middleware
func (siw *ServerInterfaceWrapper) UpdateTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInvites operation middleware
func (siw *ServerInterfaceWrapper) ListInvites(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInvites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInvite operation middleware
func (siw *ServerInterfaceWrapper) CreateInvite(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInvite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeInvite operation middleware
func (siw *ServerInterfaceWrapper) RevokeInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "inviteId" -------------
	var inviteId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "inviteId", r.PathValue("inviteId"), &inviteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "inviteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeInvite(w, r, inviteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMembers operation middleware
func (siw *ServerInterfaceWrapper) ListMembers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMembers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveMember(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMember(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTenant operation middleware
func (siw *ServerInterfaceWrapper) CreateTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWarehouses operation middleware
func (siw *ServerInterfaceWrapper) ListWarehouses(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWarehouses(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWarehouse operation middleware
func (siw *ServerInterfaceWrapper) CreateWarehouse(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWarehouse(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWarehouse operation middleware
func (siw *ServerInterfaceWrapper) UpdateWarehouse(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "warehouseId" -------------
	var warehouseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "warehouseId", r.PathValue("warehouseId"), &warehouseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "warehouseId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWarehouse(w, r, warehouseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/register", wrapper.Register)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/session", wrapper.GetSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/switch-tenant", wrapper.SwitchTenant)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/invites/{token}", wrapper.GetInvite)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/invites/{token}/accept", wrapper.AcceptInvite)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/partners", wrapper.ListPartners)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/partners", wrapper.CreatePartner)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/partners/{partnerId}", wrapper.GetPartner)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/partners/{partnerId}", wrapper.UpdatePartner)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/products", wrapper.ListProducts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/products", wrapper.CreateProduct)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/products/{productId}", wrapper.GetProduct)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/products/{productId}", wrapper.UpdateProduct)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/products/{productId}/batches", wrapper.ListProductBatches)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/products/{productId}/batches", wrapper.CreateBatch)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/products/{productId}/uoms", wrapper.ListProductUoms)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/products/{productId}/uoms", wrapper.CreateProductUom)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/products/{productId}/uoms/{uomId}", wrapper.DeleteProductUom)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tenant", wrapper.GetTenant)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/tenant", wrapper.UpdateTenant)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tenant/invites", wrapper.ListInvites)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tenant/invites", wrapper.CreateInvite)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/tenant/invites/{inviteId}", wrapper.RevokeInvite)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tenant/members", wrapper.ListMembers)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/tenant/members/{userId}", wrapper.RemoveMember)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/tenant/members/{userId}", wrapper.UpdateMember)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tenants", wrapper.CreateTenant)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/warehouses", wrapper.ListWarehouses)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/warehouses", wrapper.CreateWarehouse)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/warehouses/{warehouseId}", wrapper.UpdateWarehouse)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fzrb9u4lv9XCO0CkwBKnHT6ZV3shzTtzGZvmwZ5THHRBhe0dGxxIpEqSdn1DfK/X/AhWW8psSW3mPnm",
	"BykenufvHB7q0fFYFDMKVApn+ujEmOMIJHD97YozP/Hkha++EOpMnRjLwHEdiiNQ37L/XYfDt4Rw8J2p",
	"5Am4jvACiLCaOGc8wtKZOklC1Ei5jtVkITmhC+fp6UlNFjGjAvSq54zOQ+JJ9dljVALVH3Ech8TDkjA6",
	"+VMwqn7bLPLfHObO1PmvyWY/E/OvmLznnHGzkA/C4yRWD3GmzjUIlnAPEA45YH+N4DsRUjhPrvMb4zPi",
	"+0CHp+IskQFQqZ4KPpolElEmUQw8IlKCr6i5ZPI3llB/RJYoGuZ6zSfXuaM4kQHj5N8wAg2XTCKcZ4oi",
	"4Q8cEl8vY+aNwIlvCQiJ5piE4KNltr6jxtrp6ulvsfQCbTycxcAlMWo8Uz9fMvWxpPGuA99jwtfvsAT1",
	"d3HdT/oDDpEZhHw1yt1Ykf1eeSbxexibm7PZHqaZN+svjh6St/l0i/fZTDb7Ezyp1jnHEodscSOxTDQ/",
	"gCaRegr2JFmqHWDuBWQJfm76hsxzJiShi48gA+ZXmfSBeQ/gIywRozOGuU/o4g0SKyK9AM9CQIyGa/U3",
	"RnMiPByiNWCOZkqhMV+jg7N310cnJyevDh03o2wFZBFI8M+WwPFCM53MWT15HLAELXmrJ60KEBH6AehC",
	"Bs701O1Shw5Jl4TSKgNN5QVdEgmNZHIWQpeRXKsx5ZX1xOZlrzCXFHjjuh7zodY4iDhPhGQRcCP3OU5C",
	"6UznOBSQrTZjLARMzfibRJl/3/EmeHUIpbRXPadlr8YoWlSBN253hgXcsaiHmhChFe6WY6X8O9ys64iH",
	"5LksUVPs8zeb6GTRHYsauTTHnmT8lr3FosYvXjFBlOdAPngkwiEyw5FkSAaAFAUooUTWOb2kB39L21NT",
	"3CJJzZu7BYqpbFH1kjNrs7Wi53tSTkg5sH8C5jcSc/mRURkUhH/qOhH+TiLlxU5fuWqb9ktGMKESFsDV",
	"40JY4PDSqkWFUz31ZYU5BCwRnZ7jczrwgsaJrLcrt8Sg/OPreJ4BgJ4OZU4g9PUQ7PvERNerwtTKlJLq",
	"AT/SD8mhABSBEHgBwkWrACiyCGQW5lz2hmQ7uGatEkP0Jjbj67b/f4BDWQM4RCXUsoea4FU2YzOrbiET",
	"OKoL6XAF4kxWotWRJNE24KR/LHIdyR4MOu8BWvRz0ylubgPN275KZiHxtgmXriO1W2iwtRKdubFuc2j9",
	"wBaENvoZiDAJC4w2v9TBQCzEivGiWLIfu5QmfWw2oY7WjxDNgG9FJW1yU8+RQiKAvwTu2nlZjEupbBSO",
	"2bAISLwLtekabWJOgx61kWmBWbMDrc9H3qjo+i0BtCIyIBRhZJYy7i/mIIDKLWy/CPu6YF4z0qlim8wv",
	"tobdQr5S60WsHuQIKVDttvlSC39aoeGO+Z4DlsUn3wYGKSGMbDb3i0BCMu8BEYE8llAJPiIUHSxCJoTK",
	"l746b1N89dU53ErKZQz7HEkalDqchGsxbYXoPoK2jH8OwH3XjmvRgYe5ZBT9L/rqvHr91Tl8g2gSASee",
	"i5QOIKykqHii5mrF4EtQHzwi1BLjFA0ytP3MYkJPwH0NCyJkS175gvDSAXa7YmV++smzQ6fbnFxe26CR",
	"4bkV1X4G+xGhBZjsOgKHIBzXWRJYAa8tWtyAUHpwQeesyjZTljFB5aKm4nI20zqWUEnCjQ8iAgkIwZPa",
	"LDo1I8oipF6TSIg6zTYXVZ+yR2LO8ToN7l1PuFNj6qK7U6SoTgQ3uqTUkd/JHNeehzGymXVr32Y4oLhc",
	"T6OlvXAnadVAQ8IVZ3MSwliJbTVn7bnj9tQ2Wl8/A4Q9l3v51asJbe1WM5LqOH8Xq4TKKP+ItTuzbLV2",
	"V0qIVThEAiJMJfHEG4SNdzCZNnoAiFXwIhx5CefqnyUOEzAevxNxvo9iuU5DmRcC5kKHQpsbD4Ycu2pk",
	"L0QZTTyu1AyH4XEjwGxiczrB3W2t8kfhe4cvb3JK41bYmsnPCmqjGWeHeF6+H7FldWD3cTBdqjEefs7X",
	"PfueZ+ycTGue3VSaomsjqTuSbE39soE0Zc3gJZzI9Y2yW1u4NLj0nLEHAlmrgWe+Zs0GglCJ/2XHbhiI",
	"Y/IPWJsDXGKRbdEePiahJEcpYKVLoJLxNYowxQuItGUwji6ozygIgim6+fge+URtcJZIxsUxOmdUcuzJ",
	"oznhQk6RDIhAChIpAKx8piB0EQKyZ+dsjiRPZKAfPGMy0GN+Z0hnZBwdMByTI8WqBdBDhKmvB9yuY7jR",
	"hCMvJIqwAxYDVWPVZs2eDjU1ahOEUTFFHo4gPFdJorFvFz3ADM+OPPVTHCYchyjGMhAumixPVTY4J9/R",
	"gc88MTn/dPnH+8vbi0+XN8eRf3j8VfOVSAUqnBvFb3R2daGSCuDCMPPk+PT4RCmHpcyZOr8enxz/qjMa",
	"GWh5TnAig0nIFkTXZ2NmvJTSQF06V0DZVDJt3wgI+Zb5652d6ReqpE9FFZU8gXLHyauTk52tnU+yaroK",
	"7N9IqOACPjqwCo2MuiMB8lCx9/XJadNKGemTQltG3ric6Zd71xFJFGG+LrWYaHXTyyOMUnNSkzOxMesz",
	"muSm/q9w8HXV8NK9AvVND8cLN5Vt4701lDRuVanntjrQTH9aPxhI9crliV7ad7qz5W2qW+0x8nRZD3n6",
	"uNIK43+6hZH1YqkJr151Tyi36bRppTk7RRipXBxhQ2JOmKl4p4/OAmpE+TvImywc7Mugz8u6uL2ap49U",
	"bHFRrkLhats1lRpbgcmzS5cqjjanB/UGkK9oDGQEdUWTH8sNn+V5iLwA08WLXZSa9Gv3pE1HYUnaenGD",
	"IgzRv4g6GQfZsW+TMdiD4QG5aleojWt8STyNh5K41eo/kCVQEAJ5AXgPZm9EH7mKyaM+oX1q26Q9lB5w",
	"k4Xz35qtmv+RDxKTUBj5vx6+H/GOPlC2oohxxGHJHvQRjeaFouD0ZHgK7MbN6Xk74DDcswSmrNJwWOl5",
	"iKlP6ALFeAGmwL7pOv5S22mcntw3dxmX05L7Gr2aYM+DWJYbnXe2pNvgcs/0ssNrbofT+39GKPhvUq+n",
	"fYzuOTZy0bX8bYLYX9oQMtVXXNZaronSp3H2vJbYRNBQ+4tAPC3NTmJTcBWNnu8DEfIqHVSxmCJ5v5FQ",
	"gj5ATB+LZIAlwlyBLWFroYp/GHmb02ttA98S4OuNEdjGmQ2/0qMosTkCzx5R12v0WPtYW9JzewqiXNu7",
	"39KGep07pW0SlUOnqj5kgtkLgFCqsZG0Vb4SgGjyTIVW3YHQYG078Mh5USbMRuEVU6MRZDhqBlbNueKM",
	"Izn3M3m0ny78VhCWV5iBYlm3xEaV1OvuGdklnSLHfweZZ3cftJMJYat7Vfe6JGeuphQlWDjkG8jqaw8S",
	"R04CW3TIkOfn5fJj6tJ+3IRhT8VNmCPLDpSSDqrX9J8RCdjevT5IIN38HpGAJeFlSMBudVAkUDz4HhsJ",
	"pMJsFN5fDglkHMmZ+OQx681rRwI5hRnKi3dK7OdCAhuaS/6x7qGbIZPNbezu0D6oGdf2r4wd2puVIgvt",
	"P7py7Du0d9n9RN8thV7h/q0dOkY8Nheue0TjlKifwz3o6J1vyZ9tyN/KU7TEe8PKIaN94Y70yLHeKkqD",
	"Yuwlzv8EDiIDBlr/dHHYfj6Spp2vh+tIWNTLb9ypcSOC+DsW9fEcd5RI5DFqG19+WheS1OxjKF+S4/AI",
	"6UPuIvl+MgitSZ2a87eTqXcyZ76PcFk9kWS9cIlyLpPHhEU2OfEhBHNRuaiX7/TvJb3s6loqC5BDxJY/",
	"sgALfL3W1FZZu5Xhu7VVSs3/7SqUSsKbfpWmHDPXqzJQNlG85tLZLxKnA/dR5LFU6ibTtp6RjhRx0Aag",
	"uk77kRPETpGmaeKeZLrLXK64BXSg7wnqVyAdGi9qBqTtEK247MKOGQOTXWTH9l147FMMFKXk76+2ynJk",
	"ZGzmSN/HPOyqreb6P4bCRsVXPY2Mi1JpNvZLjA2F6rMaEWAO+h1htjspJPShRphVu5k8mg8dqONaN6U0",
	"dfvUIA7LHtvMsh/2GKIRTtW7Xrs7Ty5TBu0KFkxs92ury7I3hEdxWfalJj1clqUqjdOV6LwnF2ZjRcrX",
	"pyqvJ4/mzScdSq5wpuVGHyU3Q/eCpp+V3dSjacOaUmTtYxDZS2SGO8fPCWEoJFe8hjwykktNrhnCRZlR",
	"/gQ6Zfu9U52ybYCNoE00d/Ln3z03KKx4AZA/HQ/I39omfoMuNlckdtzauj1a/2ReVYoworAqdIUSKZC+",
	"WoiyV3q8MRtiHM3AYxEIZN7+oVUjG9UeGD9vho0RGzeXY3uExxxt+wuGGz6+qFvic+79K0NYX+XliaMa",
	"Xk6cLeL7q3VLrHJcKVji5DH7bLFTNzrIzRgUIgytqA2vJhgZKLQqbIoVVnkn9XdFvqYvYFVkY+6KT+Wq",
	"/pd7pXrmVrtR8oSHztSZLE+dp/un/wQAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
