// Command bundle merges the spec-first OpenAPI sources into one flat document.
//
// The API is authored across files so parallel tracks never collide on a single
// spec (docs/plans/m1-parallel.md): api/openapi.yaml holds the root plus shared
// components, and each track owns a fragment under api/paths/*.yaml with its own
// paths and components. oapi-codegen cannot generate schemas from external $ref
// files, so this tool deep-merges every fragment into api/openapi.gen.yaml - a
// generated, committed artifact that both oapi-codegen and openapi-typescript
// consume. Fragments may reference shared root components (e.g.
// #/components/responses/Unauthorized); the reference resolves after the merge.
//
// Run via `go generate ./...` from server/ (see gen.go). Do not edit
// api/openapi.gen.yaml by hand.
package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"

	"github.com/getkin/kin-openapi/openapi3"
	"gopkg.in/yaml.v3"
)

const (
	rootPath   = "api/openapi.yaml"
	fragGlob   = "api/paths/*.yaml"
	outputPath = "api/openapi.gen.yaml"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "bundle:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := loadYAML(rootPath)
	if err != nil {
		return err
	}

	frags, err := filepath.Glob(fragGlob)
	if err != nil {
		return err
	}
	sort.Strings(frags)

	for _, f := range frags {
		frag, err := loadYAML(f)
		if err != nil {
			return err
		}
		if err := mergePaths(root, frag, f); err != nil {
			return err
		}
		if err := mergeComponents(root, frag, f); err != nil {
			return err
		}
	}

	if err := writeYAML(outputPath, root, frags); err != nil {
		return err
	}

	// Validate the bundled result so a broken $ref or malformed fragment fails
	// here rather than deep inside a code generator.
	loader := openapi3.NewLoader()
	doc, err := loader.LoadFromFile(outputPath)
	if err != nil {
		return fmt.Errorf("validate %s: %w", outputPath, err)
	}
	if err := doc.Validate(context.Background()); err != nil {
		return fmt.Errorf("validate %s: %w", outputPath, err)
	}

	fmt.Printf("bundle: %s <- %s + %d fragment(s)\n", outputPath, rootPath, len(frags))
	return nil
}

func loadYAML(path string) (map[string]any, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var m map[string]any
	if err := yaml.Unmarshal(raw, &m); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if m == nil {
		m = map[string]any{}
	}
	return m, nil
}

// mergePaths folds a fragment's paths into root. Two fragments claiming the same
// path is a bug: each track owns distinct paths.
func mergePaths(root, frag map[string]any, name string) error {
	fp, ok := frag["paths"].(map[string]any)
	if !ok {
		return nil
	}
	rp, ok := root["paths"].(map[string]any)
	if !ok {
		rp = map[string]any{}
		root["paths"] = rp
	}
	for k, v := range fp {
		if _, dup := rp[k]; dup {
			return fmt.Errorf("%s: duplicate path %q already defined elsewhere", name, k)
		}
		rp[k] = v
	}
	return nil
}

// mergeComponents folds a fragment's components (schemas, responses, parameters,
// requestBodies, headers, ...) into root. A name reused across files is allowed
// only when the definitions are identical; a genuine clash is a bug.
func mergeComponents(root, frag map[string]any, name string) error {
	fc, ok := frag["components"].(map[string]any)
	if !ok {
		return nil
	}
	rc, ok := root["components"].(map[string]any)
	if !ok {
		rc = map[string]any{}
		root["components"] = rc
	}
	for section, defsAny := range fc {
		defs, ok := defsAny.(map[string]any)
		if !ok {
			continue
		}
		rsec, ok := rc[section].(map[string]any)
		if !ok {
			rsec = map[string]any{}
			rc[section] = rsec
		}
		for defName, def := range defs {
			if existing, dup := rsec[defName]; dup && !reflect.DeepEqual(existing, def) {
				return fmt.Errorf("%s: conflicting definition for components.%s.%s", name, section, defName)
			}
			rsec[defName] = def
		}
	}
	return nil
}

func writeYAML(path string, doc map[string]any, frags []string) error {
	body, err := yaml.Marshal(doc)
	if err != nil {
		return err
	}
	header := fmt.Sprintf(
		"# GENERATED by cmd/bundle - DO NOT EDIT.\n"+
			"# Sources: %s + %s\n"+
			"# Edit those, then run `go generate ./...` from server/.\n\n",
		rootPath, fragGlob)
	return os.WriteFile(path, append([]byte(header), body...), 0o644)
}
